### ISSUE TITLE
Error when running inference on V100 GPU

### ISSUE THREAD

**Issue by ola0x** [ultralytics/yolov5#10046]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### Bug

This is the error I get

YOLOv5 🚀 v6.2-215-g575055c Python-3.9.4 torch-1.13.0+cu117 CUDA:0 (Tesla V100-SXM2-16GB, 16161MiB)

Fusing layers... 
Traceback (most recent call last):
  File "/home/ec2-user/ai/yolov5/detect.py", line 258, in <module>
    main(opt)
  File "/home/ec2-user/ai/yolov5/detect.py", line 253, in main
    run(**vars(opt))
  File "/opt/conda/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/ec2-user/ai/yolov5/detect.py", line 95, in run
    model = DetectMultiBackend(weights, device=device, dnn=dnn, data=data, fp16=half)
  File "/home/ec2-user/ai/yolov5/models/common.py", line 345, in __init__
    model = attempt_load(weights if isinstance(weights, list) else w, device=device, inplace=True, fuse=fuse)
  File "/home/ec2-user/ai/yolov5/models/experimental.py", line 88, in attempt_load
    model.append(ckpt.fuse().eval() if fuse and hasattr(ckpt, 'fuse') else ckpt.eval())  # model in eval mode
  File "/home/ec2-user/ai/yolov5/models/yolo.py", line 144, in fuse
    m.conv = fuse_conv_and_bn(m.conv, m.bn)  # update conv
  File "/home/ec2-user/ai/yolov5/utils/torch_utils.py", line 261, in fuse_conv_and_bn
    fusedconv.weight.copy_(torch.mm(w_bn, w_conv).view(fusedconv.weight.shape))
RuntimeError: CUDA error: CUBLAS_STATUS_INVALID_VALUE when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`

### Environment

-YOLO: YOLOv5 🚀 v6.2-215-g575055c Python-3.9.4 torch-1.13.0+cu117 CUDA:0 (Tesla V100-SXM2-16GB, 16161MiB)

### Minimal Reproducible Example

```
!python detect.py --weights runs/train/waste_ai/exp/weights/best.pt --source ../waste_ai/test_vid/out_vid2.mp4 --conf 0.4 --device 0 --project runs/detect/waste_ai
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@ola0x it appears you may have environment problems. Please ensure you meet all dependency requirements if you are attempting to run YOLOv5 locally.  If in doubt, create a new virtual [Python 3.9](https://www.python.org/) environment, clone the latest repo ([code changes daily](https://github.com/ultralytics/yolov5/commits/master)), and `pip install` [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) again from scratch.

💡 ProTip! Try one of our verified environments below if you are having trouble with your local environment.


## Requirements

[**Python>=3.7.0**](https://www.python.org/) with all [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) installed including [**PyTorch>=1.7**](https://pytorch.org/get-started/locally/). To get started:
```bash
git clone https://github.com/ultralytics/yolov5  # clone
cd yolov5
pip install -r requirements.txt  # install
```

[Models](https://github.com/ultralytics/yolov5/tree/master/models) and [datasets](https://github.com/ultralytics/yolov5/tree/master/data) download automatically from the latest YOLOv5 [release](https://github.com/ultralytics/yolov5/releases) when first requested.

## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Notebooks** with free GPU: <a href="https://bit.ly/yolov5-paperspace-notebook"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"></a> <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>


## Status

<a href="https://github.com/ultralytics/yolov5/actions/workflows/ci-testing.yml"><img src="https://github.com/ultralytics/yolov5/actions/workflows/ci-testing.yml/badge.svg" alt="YOLOv5 CI"></a>

If this badge is green, all [YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions) Continuous Integration (CI) tests are currently passing. CI tests verify correct operation of YOLOv5 [training](https://github.com/ultralytics/yolov5/blob/master/train.py), [validation](https://github.com/ultralytics/yolov5/blob/master/val.py), [inference](https://github.com/ultralytics/yolov5/blob/master/detect.py), [export](https://github.com/ultralytics/yolov5/blob/master/export.py) and [benchmarks](https://github.com/ultralytics/yolov5/blob/master/benchmarks.py) on MacOS, Windows, and Ubuntu every 24 hours and on every commit.

**Comment by ola0x** [comment]
@glenn-jocher I have the env setup correctly.
It is the same env I used for training the model.

**Comment by glenn-jocher** [comment]
@ola0x well your command looks correct. Your error message is indicating a CUDA error that usually means CUDA or CUDNN is not installed/configured incorrectly, or torch is not setup up to use your CUDA version. See https://pytorch.org/get-started/locally/

**Comment by serOMENdev** [comment]
I downgraded the torch version to 1.12.1 and everything worked (in requirements.txt torch>=1.7)

**Comment by PrinceP** [comment]
https://discuss.pytorch.org/t/runtimeerror-cuda-error-cublas-status-invalid-value-when-calling-cublassgemm-handle-opa-opb-m-n-k-alpha-a-lda-b-ldb-beta-c-ldc/124544

**Comment by elviswxy** [comment]
I found a solution for my side. You can try it to see if it works. I uninstall package `pip uninstall nvidia-cublas-cu11`, and then re-install it. It works. I tested it on `pytorch1.13 + coda 11.7` and `pytorch1.13 + coda 11.6`. Here some logs:

My environment:

```
(yolov5) xwu@gpu6:~/project/yolov5$ python -m torch.utils.collect_env
Collecting environment information...
PyTorch version: 1.13.1+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.10.9 (main, Mar  8 2023, 10:47:38) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.4.0-122-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 11.6.55
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration:
GPU 0: NVIDIA A100 80GB PCIe
GPU 1: NVIDIA A100 80GB PCIe
GPU 2: NVIDIA A100 80GB PCIe
GPU 3: NVIDIA A100 80GB PCIe
GPU 4: NVIDIA A100 80GB PCIe
GPU 5: NVIDIA A100 80GB PCIe
GPU 6: NVIDIA A100 80GB PCIe
GPU 7: NVIDIA A100 80GB PCIe

Nvidia driver version: 515.65.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.24.2
[pip3] torch==1.13.1
[pip3] torchvision==0.14.1
[conda] numpy                     1.24.2                   pypi_0    pypi
[conda] torch                     1.13.1                   pypi_0    pypi
[conda] torchvision               0.14.1                   pypi_0    pypi
```

My test with errors:

```
(yolov5) xwu@gpu6:~/project/yolov5$ python train.py --img 640 --device 3 --batch 32 --epochs 5 --data coco128.yaml --weights yolov5s.pt --name test
train: weights=yolov5s.pt, cfg=, data=coco128.yaml, hyp=data/hyps/hyp.scratch-low.yaml, epochs=5, batch_size=32, imgsz=640, rect=False, resume=False, nosave=False, noval=False, noautoanchor=False, noplots=False, evolve=None, bucket=, cache=None, image_weights=False, device=3, multi_scale=False, single_cls=False, optimizer=SGD, sync_bn=False, workers=8, project=runs/train, name=test, exist_ok=False, quad=False, cos_lr=False, label_smoothing=0.0, patience=100, freeze=[0], save_period=-1, seed=0, local_rank=-1, entity=None, upload_dataset=False, bbox_interval=-1, artifact_alias=latest
github: ⚠️ YOLOv5 is out of date by 4 commits. Use 'git pull' or 'git clone https://github.com/ultralytics/yolov5' to update.
YOLOv5 🚀 v7.0-116-g5c91dae Python-3.10.9 torch-1.13.1+cu117 CUDA:3 (NVIDIA A100 80GB PCIe, 81112MiB)

hyperparameters: lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=0.05, cls=0.5, cls_pw=1.0, obj=1.0, obj_pw=1.0, iou_t=0.2, anchor_t=4.0, fl_gamma=0.0, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0
ClearML: run 'pip install clearml' to automatically track, visualize and remotely train YOLOv5 🚀 in ClearML
Comet: run 'pip install comet_ml' to automatically track and visualize YOLOv5 🚀 runs in Comet
TensorBoard: Start with 'tensorboard --logdir runs/train', view at http://localhost:6006/

                 from  n    params  module                                  arguments
  0                -1  1      3520  models.common.Conv                      [3, 32, 6, 2, 2]
  1                -1  1     18560  models.common.Conv                      [32, 64, 3, 2]
  2                -1  1     18816  models.common.C3                        [64, 64, 1]
  3                -1  1     73984  models.common.Conv                      [64, 128, 3, 2]
  4                -1  2    115712  models.common.C3                        [128, 128, 2]
  5                -1  1    295424  models.common.Conv                      [128, 256, 3, 2]
  6                -1  3    625152  models.common.C3                        [256, 256, 3]
  7                -1  1   1180672  models.common.Conv                      [256, 512, 3, 2]
  8                -1  1   1182720  models.common.C3                        [512, 512, 1]
  9                -1  1    656896  models.common.SPPF                      [512, 512, 5]
 10                -1  1    131584  models.common.Conv                      [512, 256, 1, 1]
 11                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']
 12           [-1, 6]  1         0  models.common.Concat                    [1]
 13                -1  1    361984  models.common.C3                        [512, 256, 1, False]
 14                -1  1     33024  models.common.Conv                      [256, 128, 1, 1]
 15                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']
 16           [-1, 4]  1         0  models.common.Concat                    [1]
 17                -1  1     90880  models.common.C3                        [256, 128, 1, False]
 18                -1  1    147712  models.common.Conv                      [128, 128, 3, 2]
 19          [-1, 14]  1         0  models.common.Concat                    [1]
 20                -1  1    296448  models.common.C3                        [256, 256, 1, False]
 21                -1  1    590336  models.common.Conv                      [256, 256, 3, 2]
 22          [-1, 10]  1         0  models.common.Concat                    [1]
 23                -1  1   1182720  models.common.C3                        [512, 512, 1, False]
 24      [17, 20, 23]  1    229245  models.yolo.Detect                      [80, [[10, 13, 16, 30, 33, 23], [30, 61, 62, 45, 59, 119], [116, 90, 156, 198, 373, 326]], [128, 256, 512]]
Model summary: 214 layers, 7235389 parameters, 7235389 gradients, 16.6 GFLOPs

Transferred 349/349 items from yolov5s.pt
AMP: checks passed ✅
optimizer: SGD(lr=0.01) with parameter groups 57 weight(decay=0.0), 60 weight(decay=0.0005), 60 bias
train: Scanning /home/xwu/project/datasets/coco128/labels/train2017.cache... 126 images, 2 backgrounds, 0 corrupt: 100%
val: Scanning /home/xwu/project/datasets/coco128/labels/train2017.cache... 126 images, 2 backgrounds, 0 corrupt: 100%|█

AutoAnchor: 4.27 anchors/target, 0.994 Best Possible Recall (BPR). Current anchors are a good fit to dataset ✅
Plotting labels to runs/train/test5/labels.jpg...
Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to runs/train/test5
Starting training for 5 epochs...

      Epoch    GPU_mem   box_loss   obj_loss   cls_loss  Instances       Size
        0/4      7.01G    0.04476    0.05961    0.01655        455        640: 100%|██████████| 4/4 [00:07<00:00,  1.94
                 Class     Images  Instances          P          R      mAP50   mAP50-95: 100%|██████████| 2/2 [00:00<0
                   all        128        929      0.636      0.587      0.664      0.438

      Epoch    GPU_mem   box_loss   obj_loss   cls_loss  Instances       Size
        1/4      9.36G    0.04508     0.0668    0.01501        405        640: 100%|██████████| 4/4 [00:00<00:00,  6.97
                 Class     Images  Instances          P          R      mAP50   mAP50-95: 100%|██████████| 2/2 [00:00<0
                   all        128        929      0.678      0.612       0.69      0.458

      Epoch    GPU_mem   box_loss   obj_loss   cls_loss  Instances       Size
        2/4      9.36G    0.04449    0.06286    0.01439        413        640: 100%|██████████| 4/4 [00:00<00:00,  6.75
                 Class     Images  Instances          P          R      mAP50   mAP50-95: 100%|██████████| 2/2 [00:00<0
                   all        128        929      0.745      0.622      0.718      0.479

      Epoch    GPU_mem   box_loss   obj_loss   cls_loss  Instances       Size
        3/4      9.36G    0.04421    0.06805    0.01598        440        640: 100%|██████████| 4/4 [00:00<00:00,  7.45
                 Class     Images  Instances          P          R      mAP50   mAP50-95: 100%|██████████| 2/2 [00:00<0
                   all        128        929      0.758      0.624      0.728      0.487

      Epoch    GPU_mem   box_loss   obj_loss   cls_loss  Instances       Size
        4/4      9.36G    0.04229    0.06131    0.01462        416        640: 100%|██████████| 4/4 [00:00<00:00,  7.45
                 Class     Images  Instances          P          R      mAP50   mAP50-95: 100%|██████████| 2/2 [00:00<0
                   all        128        929      0.784      0.639      0.748      0.497

5 epochs completed in 0.006 hours.
Optimizer stripped from runs/train/test5/weights/last.pt, 14.9MB
Optimizer stripped from runs/train/test5/weights/best.pt, 14.9MB

Validating runs/train/test5/weights/best.pt...
Fusing layers...
Traceback (most recent call last):
  File "/home/xwu/project/yolov5/train.py", line 640, in <module>
    main(opt)
  File "/home/xwu/project/yolov5/train.py", line 529, in main
    train(opt.hyp, opt, device, callbacks)
  File "/home/xwu/project/yolov5/train.py", line 416, in train
    model=attempt_load(f, device).half(),
  File "/home/xwu/project/yolov5/models/experimental.py", line 88, in attempt_load
    model.append(ckpt.fuse().eval() if fuse and hasattr(ckpt, 'fuse') else ckpt.eval())  # model in eval mode
  File "/home/xwu/project/yolov5/models/yolo.py", line 144, in fuse
    m.conv = fuse_conv_and_bn(m.conv, m.bn)  # update conv
  File "/home/xwu/project/yolov5/utils/torch_utils.py", line 262, in fuse_conv_and_bn
    fusedconv.weight.copy_(torch.mm(w_bn, w_conv).view(fusedconv.weight.shape))
RuntimeError: CUDA error: CUBLAS_STATUS_INVALID_VALUE when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`
```

My test with solution:

```
(yolov5) xwu@gpu6:~/project/yolov5$ pip uninstall nvidia-cublas-cu11
Found existing installation: nvidia-cublas-cu11 11.10.3.66
Uninstalling nvidia-cublas-cu11-11.10.3.66:
  Would remove:
    /home/xwu/anaconda3/envs/yolov5/lib/python3.10/site-packages/nvidia/cublas/include/cublas.h
    /home/xwu/anaconda3/envs/yolov5/lib/python3.10/site-packages/nvidia/cublas/include/cublasLt.h
    /home/xwu/anaconda3/envs/yolov5/lib/python3.10/site-packages/nvidia/cublas/include/cublasXt.h
    /home/xwu/anaconda3/envs/yolov5/lib/python3.10/site-packages/nvidia/cublas/include/cublas_api.h
    /home/xwu/anaconda3/envs/yolov5/lib/python3.10/site-packages/nvidia/cublas/include/cublas_v2.h
    /home/xwu/anaconda3/envs/yolov5/lib/python3.10/site-packages/nvidia/cublas/include/nvblas.h
    /home/xwu/anaconda3/envs/yolov5/lib/python3.10/site-packages/nvidia/cublas/lib/libcublas.so.11
    /home/xwu/anaconda3/envs/yolov5/lib/python3.10/site-packages/nvidia/cublas/lib/libcublasLt.so.11
    /home/xwu/anaconda3/envs/yolov5/lib/python3.10/site-packages/nvidia/cublas/lib/libnvblas.so.11
    /home/xwu/anaconda3/envs/yolov5/lib/python3.10/site-packages/nvidia_cublas_cu11-11.10.3.66.dist-info/*
Proceed (Y/n)? Y
  Successfully uninstalled nvidia-cublas-cu11-11.10.3.66
(yolov5) xwu@gpu6:~/project/yolov5$ python train.py --img 640 --device 3 --batch 32 --epochs 5 --data coco128.yaml --weights yolov5s.pt --name test
train: weights=yolov5s.pt, cfg=, data=coco128.yaml, hyp=data/hyps/hyp.scratch-low.yaml, epochs=5, batch_size=32, imgsz=640, rect=False, resume=False, nosave=False, noval=False, noautoanchor=False, noplots=False, evolve=None, bucket=, cache=None, image_weights=False, device=3, multi_scale=False, single_cls=False, optimizer=SGD, sync_bn=False, workers=8, project=runs/train, name=test, exist_ok=False, quad=False, cos_lr=False, label_smoothing=0.0, patience=100, freeze=[0], save_period=-1, seed=0, local_rank=-1, entity=None, upload_dataset=False, bbox_interval=-1, artifact_alias=latest
github: ⚠️ YOLOv5 is out of date by 4 commits. Use 'git pull' or 'git clone https://github.com/ultralytics/yolov5' to update.
requirements: YOLOv5 requirements "thop>=0.1.1" "torch>=1.7.0" "torchvision>=0.8.1" not found, attempting AutoUpdate...
Requirement already satisfied: thop>=0.1.1 in /home/xwu/anaconda3/envs/yolov5/lib/python3.10/site-packages (0.1.1.post2209072238)
Requirement already satisfied: torch>=1.7.0 in /home/xwu/anaconda3/envs/yolov5/lib/python3.10/site-packages (1.13.1)
Requirement already satisfied: torchvision>=0.8.1 in /home/xwu/anaconda3/envs/yolov5/lib/python3.10/site-packages (0.14.1)
Requirement already satisfied: nvidia-cuda-nvrtc-cu11==11.7.99 in /home/xwu/anaconda3/envs/yolov5/lib/python3.10/site-packages (from torch>=1.7.0) (11.7.99)
Collecting nvidia-cublas-cu11==11.10.3.66
  Using cached nvidia_cublas_cu11-11.10.3.66-py3-none-manylinux1_x86_64.whl (317.1 MB)
Requirement already satisfied: nvidia-cuda-runtime-cu11==11.7.99 in /home/xwu/anaconda3/envs/yolov5/lib/python3.10/site-packages (from torch>=1.7.0) (11.7.99)
Requirement already satisfied: typing-extensions in /home/xwu/anaconda3/envs/yolov5/lib/python3.10/site-packages (from torch>=1.7.0) (4.5.0)
Requirement already satisfied: nvidia-cudnn-cu11==8.5.0.96 in /home/xwu/anaconda3/envs/yolov5/lib/python3.10/site-packages (from torch>=1.7.0) (8.5.0.96)
Requirement already satisfied: setuptools in /home/xwu/anaconda3/envs/yolov5/lib/python3.10/site-packages (from nvidia-cublas-cu11==11.10.3.66->torch>=1.7.0) (65.6.3)
Requirement already satisfied: wheel in /home/xwu/anaconda3/envs/yolov5/lib/python3.10/site-packages (from nvidia-cublas-cu11==11.10.3.66->torch>=1.7.0) (0.38.4)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /home/xwu/anaconda3/envs/yolov5/lib/python3.10/site-packages (from torchvision>=0.8.1) (9.4.0)
Requirement already satisfied: requests in /home/xwu/anaconda3/envs/yolov5/lib/python3.10/site-packages (from torchvision>=0.8.1) (2.28.2)
Requirement already satisfied: numpy in /home/xwu/anaconda3/envs/yolov5/lib/python3.10/site-packages (from torchvision>=0.8.1) (1.24.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/xwu/anaconda3/envs/yolov5/lib/python3.10/site-packages (from requests->torchvision>=0.8.1) (3.1.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/xwu/anaconda3/envs/yolov5/lib/python3.10/site-packages (from requests->torchvision>=0.8.1) (1.26.14)
Requirement already satisfied: idna<4,>=2.5 in /home/xwu/anaconda3/envs/yolov5/lib/python3.10/site-packages (from requests->torchvision>=0.8.1) (3.4)
Requirement already satisfied: certifi>=2017.4.17 in /home/xwu/anaconda3/envs/yolov5/lib/python3.10/site-packages (from requests->torchvision>=0.8.1) (2022.12.7)
Installing collected packages: nvidia-cublas-cu11
Successfully installed nvidia-cublas-cu11-11.10.3.66

requirements: 3 packages updated per /home/xwu/project/yolov5/requirements.txt
requirements: ⚠️ Restart runtime or rerun command for updates to take effect

YOLOv5 🚀 v7.0-116-g5c91dae Python-3.10.9 torch-1.13.1+cu117 CUDA:3 (NVIDIA A100 80GB PCIe, 81112MiB)

hyperparameters: lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=0.05, cls=0.5, cls_pw=1.0, obj=1.0, obj_pw=1.0, iou_t=0.2, anchor_t=4.0, fl_gamma=0.0, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0
ClearML: run 'pip install clearml' to automatically track, visualize and remotely train YOLOv5 🚀 in ClearML
Comet: run 'pip install comet_ml' to automatically track and visualize YOLOv5 🚀 runs in Comet
TensorBoard: Start with 'tensorboard --logdir runs/train', view at http://localhost:6006/

                 from  n    params  module                                  arguments
  0                -1  1      3520  models.common.Conv                      [3, 32, 6, 2, 2]
  1                -1  1     18560  models.common.Conv                      [32, 64, 3, 2]
  2                -1  1     18816  models.common.C3                        [64, 64, 1]
  3                -1  1     73984  models.common.Conv                      [64, 128, 3, 2]
  4                -1  2    115712  models.common.C3                        [128, 128, 2]
  5                -1  1    295424  models.common.Conv                      [128, 256, 3, 2]
  6                -1  3    625152  models.common.C3                        [256, 256, 3]
  7                -1  1   1180672  models.common.Conv                      [256, 512, 3, 2]
  8                -1  1   1182720  models.common.C3                        [512, 512, 1]
  9                -1  1    656896  models.common.SPPF                      [512, 512, 5]
 10                -1  1    131584  models.common.Conv                      [512, 256, 1, 1]
 11                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']
 12           [-1, 6]  1         0  models.common.Concat                    [1]
 13                -1  1    361984  models.common.C3                        [512, 256, 1, False]
 14                -1  1     33024  models.common.Conv                      [256, 128, 1, 1]
 15                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']
 16           [-1, 4]  1         0  models.common.Concat                    [1]
 17                -1  1     90880  models.common.C3                        [256, 128, 1, False]
 18                -1  1    147712  models.common.Conv                      [128, 128, 3, 2]
 19          [-1, 14]  1         0  models.common.Concat                    [1]
 20                -1  1    296448  models.common.C3                        [256, 256, 1, False]
 21                -1  1    590336  models.common.Conv                      [256, 256, 3, 2]
 22          [-1, 10]  1         0  models.common.Concat                    [1]
 23                -1  1   1182720  models.common.C3                        [512, 512, 1, False]
 24      [17, 20, 23]  1    229245  models.yolo.Detect                      [80, [[10, 13, 16, 30, 33, 23], [30, 61, 62, 45, 59, 119], [116, 90, 156, 198, 373, 326]], [128, 256, 512]]
Model summary: 214 layers, 7235389 parameters, 7235389 gradients, 16.6 GFLOPs

Transferred 349/349 items from yolov5s.pt
AMP: checks passed ✅
optimizer: SGD(lr=0.01) with parameter groups 57 weight(decay=0.0), 60 weight(decay=0.0005), 60 bias
train: Scanning /home/xwu/project/datasets/coco128/labels/train2017.cache... 126 images, 2 backgrounds, 0 corrupt: 100%
val: Scanning /home/xwu/project/datasets/coco128/labels/train2017.cache... 126 images, 2 backgrounds, 0 corrupt: 100%|█

AutoAnchor: 4.27 anchors/target, 0.994 Best Possible Recall (BPR). Current anchors are a good fit to dataset ✅
Plotting labels to runs/train/test6/labels.jpg...
Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to runs/train/test6
Starting training for 5 epochs...

      Epoch    GPU_mem   box_loss   obj_loss   cls_loss  Instances       Size
        0/4      7.01G    0.04476    0.05961    0.01655        455        640: 100%|██████████| 4/4 [00:08<00:00,  2.01
                 Class     Images  Instances          P          R      mAP50   mAP50-95: 100%|██████████| 2/2 [00:00<0
                   all        128        929      0.636      0.587      0.664      0.438

      Epoch    GPU_mem   box_loss   obj_loss   cls_loss  Instances       Size
        1/4      9.36G    0.04508     0.0668    0.01501        405        640: 100%|██████████| 4/4 [00:00<00:00,  7.13
                 Class     Images  Instances          P          R      mAP50   mAP50-95: 100%|██████████| 2/2 [00:00<0
                   all        128        929      0.678      0.612       0.69      0.458

      Epoch    GPU_mem   box_loss   obj_loss   cls_loss  Instances       Size
        2/4      9.36G    0.04449    0.06286    0.01439        413        640: 100%|██████████| 4/4 [00:00<00:00,  6.84
                 Class     Images  Instances          P          R      mAP50   mAP50-95: 100%|██████████| 2/2 [00:00<0
                   all        128        929      0.745      0.622      0.718      0.479

      Epoch    GPU_mem   box_loss   obj_loss   cls_loss  Instances       Size
        3/4      9.36G    0.04421    0.06805    0.01598        440        640: 100%|██████████| 4/4 [00:00<00:00,  6.02
                 Class     Images  Instances          P          R      mAP50   mAP50-95: 100%|██████████| 2/2 [00:00<0
                   all        128        929      0.758      0.624      0.728      0.487

      Epoch    GPU_mem   box_loss   obj_loss   cls_loss  Instances       Size
        4/4      9.36G    0.04229    0.06131    0.01462        416        640: 100%|██████████| 4/4 [00:00<00:00,  5.86
                 Class     Images  Instances          P          R      mAP50   mAP50-95: 100%|██████████| 2/2 [00:00<0
                   all        128        929      0.784      0.639      0.748      0.497

5 epochs completed in 0.006 hours.
Optimizer stripped from runs/train/test6/weights/last.pt, 14.9MB
Optimizer stripped from runs/train/test6/weights/best.pt, 14.9MB

Validating runs/train/test6/weights/best.pt...
Fusing layers...
Model summary: 157 layers, 7225885 parameters, 0 gradients, 16.4 GFLOPs
                 Class     Images  Instances          P          R      mAP50   mAP50-95: 100%|██████████| 2/2 [00:04<0
                   all        128        929      0.788       0.64      0.749      0.497
                person        128        254      0.877      0.705      0.802      0.533
               bicycle        128          6      0.767      0.557      0.753      0.421
                   car        128         46      0.738      0.435      0.558      0.229
            motorcycle        128          5       0.77          1      0.928      0.668
              airplane        128          6          1      0.961      0.995      0.714
                   bus        128          7      0.668      0.714      0.761      0.666
                 train        128          3      0.562      0.333       0.83      0.462
                 truck        128         12      0.672      0.417      0.486      0.277
                  boat        128          6          1       0.36        0.6      0.245
         traffic light        128         14      0.788      0.268      0.412      0.214
             stop sign        128          2      0.827          1      0.995      0.822
                 bench        128          9      0.822      0.519      0.639       0.28
                  bird        128         16      0.981          1      0.995      0.679
                   cat        128          4      0.886          1      0.995      0.772
                   dog        128          9      0.971      0.667      0.913      0.655
                 horse        128          2      0.859          1      0.995      0.622
              elephant        128         17      0.923      0.882      0.932      0.717
                  bear        128          1      0.701          1      0.995      0.995
                 zebra        128          4       0.86          1      0.995      0.931
               giraffe        128          9       0.76      0.778        0.9      0.754
              backpack        128          6      0.849      0.667      0.772      0.286
              umbrella        128         18       0.87      0.744      0.872      0.521
               handbag        128         19          1      0.292      0.398      0.222
                   tie        128          7      0.999      0.714      0.782      0.501
              suitcase        128          4      0.644       0.75      0.787      0.563
               frisbee        128          5      0.721        0.8        0.8      0.721
                  skis        128          1      0.867          1      0.995      0.203
             snowboard        128          7      0.816      0.714      0.855      0.562
           sports ball        128          6      0.659      0.667      0.602      0.333
                  kite        128         10      0.695       0.46      0.593      0.211
          baseball bat        128          4          1       0.47      0.537      0.205
        baseball glove        128          7      0.492      0.429      0.468      0.308
            skateboard        128          5          1      0.599      0.758      0.496
         tennis racket        128          7      0.796      0.429      0.513      0.307
                bottle        128         18      0.555      0.347      0.539      0.257
            wine glass        128         16       0.76      0.875        0.9      0.485
                   cup        128         36      0.843      0.597       0.82       0.53
                  fork        128          6          1      0.326      0.429      0.335
                 knife        128         16      0.767      0.618      0.741      0.409
                 spoon        128         22      0.844      0.492      0.631      0.383
                  bowl        128         28      0.842      0.571      0.715      0.514
                banana        128          1      0.838          1      0.995      0.211
              sandwich        128          2          1          0      0.662      0.629
                orange        128          4          1      0.976      0.995      0.635
              broccoli        128         11      0.517      0.364      0.457      0.339
                carrot        128         24      0.695      0.625       0.73      0.487
               hot dog        128          2      0.517          1      0.995       0.92
                 pizza        128          5      0.843        0.8      0.962      0.721
                 donut        128         14       0.68          1      0.954      0.831
                  cake        128          4       0.86          1      0.995      0.803
                 chair        128         35       0.58        0.6      0.647      0.334
                 couch        128          6      0.893      0.667      0.832       0.56
          potted plant        128         14      0.738      0.786      0.836      0.505
                   bed        128          3      0.779      0.333      0.753      0.416
          dining table        128         13      0.803      0.315      0.596      0.321
                toilet        128          2       0.81          1      0.995      0.895
                    tv        128          2      0.583          1      0.995      0.796
                laptop        128          3          1          0       0.58      0.305
                 mouse        128          2          1          0      0.173     0.0864
                remote        128          8          1      0.624      0.635      0.551
            cell phone        128          8      0.604      0.383      0.431      0.202
             microwave        128          3      0.752          1      0.995      0.799
                  oven        128          5      0.404        0.4      0.439      0.299
                  sink        128          6      0.495      0.328       0.36      0.277
          refrigerator        128          5      0.545        0.8      0.798      0.565
                  book        128         29      0.655      0.241      0.344      0.157
                 clock        128          9      0.809      0.889      0.932      0.715
                  vase        128          2      0.488          1      0.995      0.846
              scissors        128          1          1          0      0.497     0.0578
            teddy bear        128         21      0.859      0.583      0.801       0.52
            toothbrush        128          5      0.721        0.6      0.828      0.514
Results saved to runs/train/test6
```
