### ISSUE TITLE
Cuda tried allocating an enormous amount of memory (1936GiB)

### ISSUE THREAD

**Issue by BilboBaguette** [ultralytics/yolov5#10528]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Training

### Bug

Hi, new to YOLO, I am getting this error message when training YOLOv5x6:

torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1936.00 GiB (GPU 1; 11.17 GiB total capacity; 2.15 GiB already allocated; 7.62 GiB free; 3.02 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

For context, I am trying to train YOLOv5x6 on the PubLayNet datatset (article [here](https://arxiv.org/pdf/1908.07836.pdf), github [here](https://github.com/ibm-aur-nlp/PubLayNet)) to compare the results with the DocLayNet dataset that has already been tested on YOLOv5x6 (article [here](https://arxiv.org/pdf/2206.01062.pdf), github [here](https://github.com/DS4SD/DocLayNet))

I am doing this using base image size of 640, batch size of 8 and running distributed data parallel mode on 2 K80 GPUs. 
During training, memory usage is normal as can be seen below:

![image](https://user-images.githubusercontent.com/44286703/208399478-4206637b-5206-4d33-baee-cde4d2955832.png)
![image](https://user-images.githubusercontent.com/44286703/208399647-11ce378d-565e-4fd9-a32c-c99b5f298cc0.png)

But about 80% through the first epoch I get the above error message. Any clues as to why the model would try to allocate such an enormous amount of memory and how to fix it ?

### Environment

- Yolo : Yolov5x6
- OS : Ubuntu 20.04
- Python : 3.9.12

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@BilboBaguette 👋 Hello! Thanks for asking about **CUDA memory issues**. YOLOv5 🚀 can be trained on CPU, [single-GPU](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data), or [multi-GPU](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training). When training on GPU it is important to keep your batch-size small enough that you do not use all of your GPU memory, otherwise you will see a CUDA Out Of Memory (OOM) Error and your training will crash. You can observe your CUDA memory utilization using either the `nvidia-smi` command or by viewing your console output:

<img width="800" alt="Screenshot 2021-05-28 at 12 19 51" src="https://user-images.githubusercontent.com/26833433/131122318-8141d1ce-13de-44bf-bbdc-487bad442ff0.png">

### CUDA Out of Memory Solutions

If you encounter a CUDA OOM error, the steps you can take to reduce your memory usage are:

- Reduce `--batch-size`
- Reduce `--img-size`
- Reduce model size, i.e. from YOLOv5x -> YOLOv5l -> YOLOv5m -> YOLOv5s > YOLOv5n
- Train with [multi-GPU](https://docs.ultralytics.com/yolov5/tutorials/multi_gpu_training) at the same `--batch-size`
- Upgrade your hardware to a larger GPU
- Train on free GPU backends with up to 16GB of CUDA memory: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>

### AutoBatch

You can use [YOLOv5 AutoBatch](https://github.com/ultralytics/yolov5/pull/5092) (NEW) to find the best batch size for your training by passing `--batch-size -1`. AutoBatch will solve for a 90% CUDA memory-utilization batch-size given your training settings. AutoBatch is experimental, and only works for Single-GPU training. It may not work on all systems, and is not recommended for production use.

<img width="1746" alt="Screenshot 2021-11-06 at 12 31 10" src="https://user-images.githubusercontent.com/26833433/140608327-9c0c0baf-a0ee-4551-a4ff-5ee26b155c51.png">

Good luck 🍀 and let us know if you have any other questions!

**Comment by Adreaming5101** [comment]
> * --batch-size

我将这个参数改成了 -1，自动处理，已经解决此问题

**Comment by glenn-jocher** [comment]
@Adreaming5101 太好了！感谢您分享解决方案。如果您有其他问题，请随时告诉我们。祝您使用 YOLOv5 顺利！ ✨
