### ISSUE TITLE
Error in training my data

### ISSUE THREAD

**Issue by Ming-Y-ANG** [ultralytics/yolov5#1312]
## ❔Question
    I have a single target dataset，There's no problem training on yolov3，But there was an error on V5，
When I use GPU, the train is ok, but An error occurred while testing as follows：
“File "/root/yolov5/utils/general.py", line 365, in bbox_iou
    inter = (torch.min(b1_x2, b2_x2) - torch.max(b1_x1, b2_x1)).clamp(0) * \
RuntimeError: CUDA error: device-side assert triggered
/pytorch/aten/src/ATen/native/cuda/IndexKernel.cu:84: operator(): block: [4,0,0], thread: [70,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
I switch to CPU   The error is as follows：
  File "/root/yolov5/test.py", line 121, in test
    loss += compute_loss([x.float() for x in train_out], targets, model)[1][:3]  # box, obj, cls
  File "/root/yolov5/utils/general.py", line 509, in compute_loss
    ps = pi[b, a, gj, gi]  # prediction subset corresponding to targets
IndexError: index 52 is out of bounds for dimension 3 with size 52

I checked my dataset and there was nothing wrong and it can be trained and tested on yolov3

**Comment by glenn-jocher** [comment]
@Ming-Y-ANG thanks for the bug report! Can you supply code to reproduce this in a Colab Notebook please? You can use this cell to get started:

```python
!git clone https://github.com/ultralytics/yolov5  # clone repo
%cd yolov5
%pip install -qr requirements.txt  # install dependencies

import torch
from IPython.display import Image, clear_output  # to display images

clear_output()
print('Setup complete. Using torch %s %s' % (torch.__version__, torch.cuda.get_device_properties(0) if torch.cuda.is_available() else 'CPU'))

# CODE TO REPRODUCE YOUR ISSUE HERE

```

**Comment by glenn-jocher** [comment]
@Ming-Y-ANG we are tracking an identical error by another user in https://github.com/ultralytics/yolov3/issues/1551 interestingly enough. 

It seems like in extremely rare cases, when training with mixed precision the index values here may experience overflow.

**Comment by glenn-jocher** [comment]
TODO: bug fix for loss function grid indices overflow.

**Comment by glenn-jocher** [comment]
@Ming-Y-ANG this issue should be resolved now in PR https://github.com/ultralytics/yolov5/pull/1313.

Please `git pull` to receive this update and retrain to verify the issue is resolved.

**Comment by Ming-Y-ANG** [comment]
![image](https://user-images.githubusercontent.com/48575506/98371978-06f7ce80-2078-11eb-8d90-e994382c5154.png)
I git clone the new project, The same error occurred

**Comment by glenn-jocher** [comment]
@Ming-Y-ANG thanks! Is this the same identical error as before or a new one? Can you run this in CPU mode to see what the error is again?

**Comment by glenn-jocher** [comment]
@Ming-Y-ANG I'm a bit confused about your error messages as the CUDA errors seem to originate in bbox_iou(), but the CPU errors occur before that on L509 `ps = pi[b, a, gj, gi]  # prediction subset corresponding to targets`.

The PR should fix `gj` and `gi` from from over or underflowing, but this would seem to be unrelated to anything is bbox_iou().

**Comment by Ming-Y-ANG** [comment]
Wait a minute. I'm running on the CPU. It's going to take a while

**Comment by Ming-Y-ANG** [comment]
![image](https://user-images.githubusercontent.com/48575506/98375109-a323d480-207c-11eb-8160-48ade60a2b88.png)

**Comment by Ming-Y-ANG** [comment]
The mistake is the same as before

**Comment by glenn-jocher** [comment]
@Ming-Y-ANG hmm ok, thanks. Can you then provide code we can run to reproduce the same error? This Colab cell can get you started.

```python
!git clone https://github.com/ultralytics/yolov5  # clone repo
%cd yolov5
%pip install -qr requirements.txt  # install dependencies

import torch
from IPython.display import Image, clear_output  # to display images

clear_output()
print('Setup complete. Using torch %s %s' % (torch.__version__, torch.cuda.get_device_properties(0) if torch.cuda.is_available() else 'CPU'))

# CODE TO REPRODUCE YOUR ISSUE HERE

```

**Comment by Ming-Y-ANG** [comment]
I did not modify the code of the project, but added / modified the necessary configuration file according to the prompt. The process of my whole project is like this:
git clone https://github.com/ultralytics/yolov5.git
cd yolov5 
cd data 
touch apple.yaml   as follow:
![image](https://user-images.githubusercontent.com/48575506/98384112-547c3780-2088-11eb-9f5b-882496b6999c.png)
modify  models/yolov5s.yaml as follow:
![image](https://user-images.githubusercontent.com/48575506/98384516-d2404300-2088-11eb-962d-77022436109e.png)
add mydataset as 
![image](https://user-images.githubusercontent.com/48575506/98384776-277c5480-2089-11eb-8872-1064ff985590.png)
python3 train.py .....
error ...
Maybe there's something wrong with my dataset. I'll see it tomorrow

**Comment by Ming-Y-ANG** [comment]
I didn't modify the code of the project, just added / modified the necessary configuration file according to the prompt. I will carefully check the data set problem tomorrow

**Comment by Ming-Y-ANG** [comment]
Another question, how can I disable the mixed precision training option in the project to verify that the previous bug is caused by this

**Comment by glenn-jocher** [comment]
@Ming-Y-ANG got it. If the dataset is small can you share it and I'll try the training in Colab?

**Comment by glenn-jocher** [comment]
@Ming-Y-ANG I think I just realized what the problem is. The PR clamps input indices to the grid size (i.e. 52 in your error), whereas I should have clamped to grid size - 1, which would be 51.

**Comment by glenn-jocher** [comment]
@Ming-Y-ANG ok, I've pushed a second PR https://github.com/ultralytics/yolov5/pull/1316 which should finally address the overflow issue. Can you git pull and retest?

**Comment by Ming-Y-ANG** [comment]
I git clone the new project ,The problem has been solved. Thank you very much

**Comment by glenn-jocher** [comment]
@Ming-Y-ANG great! 

Thanks for reporting your issues. Let us know if any other bugs pop up!
