### ISSUE TITLE
RuntimeError: cuDNN error: CUDNN_STATUS_INTERNAL_ERROR

### ISSUE THREAD

**Issue by HtutLynn** [ultralytics/yolov5#1573]
## 🐛 Bug
Hi. I just pulled the latest commits to the repo and run the same training command that I've been using until yesterday but it doesn't work anymore after pulling the latest commits. I am training on a small custom dataset with 700 images as train set and 80 images as validation set. To be extra sure, I created a new Conda environment and cloned a new repo, and tested on it but the results are still the same. 

train command
```
python train.py --img 720 --batch 64 --epochs 15 --data custom.yaml --weights yolov5s.pt --cfg ./models/single-yolov5s.yaml --single-cls --hyp ./data/hyp.finetune.yaml
```

Error output
```
Traceback (most recent call last):
  File "train.py", line 492, in <module>
    train(hyp, opt, device, tb_writer, wandb)
  File "train.py", line 287, in train
    pred = model(imgs)  # forward
  File "/anaconda/envs/train/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/altotech/yolov5/models/yolo.py", line 121, in forward
    return self.forward_once(x, profile)  # single-scale inference, train
  File "/home/altotech/yolov5/models/yolo.py", line 137, in forward_once
    x = m(x)  # run
  File "/anaconda/envs/train/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/altotech/yolov5/models/common.py", line 71, in forward
    return self.cv4(self.act(self.bn(torch.cat((y1, y2), dim=1))))
  File "/anaconda/envs/train/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/altotech/yolov5/models/common.py", line 36, in forward
    return self.act(self.bn(self.conv(x)))
  File "/anaconda/envs/train/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/anaconda/envs/train/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 423, in forward
    return self._conv_forward(input, self.weight)
  File "/anaconda/envs/train/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 419, in _conv_forward
    return F.conv2d(input, weight, self.bias, self.stride,
RuntimeError: cuDNN error: CUDNN_STATUS_INTERNAL_ERROR
You can try to repro this exception using the following code snippet. If that doesn't trigger the error, please include your original repro script when reporting this issue.

import torch
torch.backends.cuda.matmul.allow_tf32 = True
torch.backends.cudnn.benchmark = True
torch.backends.cudnn.deterministic = False
torch.backends.cudnn.allow_tf32 = True
data = torch.randn([64, 64, 184, 184], dtype=torch.half, device='cuda', requires_grad=True)
net = torch.nn.Conv2d(64, 64, kernel_size=[1, 1], padding=[0, 0], stride=[1, 1], dilation=[1, 1], groups=1)
net = net.cuda().half()
out = net(data)
out.backward(torch.randn_like(out))
torch.cuda.synchronize()

ConvolutionParams 
    data_type = CUDNN_DATA_HALF
    padding = [0, 0, 0]
    stride = [1, 1, 0]
    dilation = [1, 1, 0]
    groups = 1
    deterministic = false
    allow_tf32 = true
input: TensorDescriptor 0x5610843e4100
    type = CUDNN_DATA_HALF
    nbDims = 4
    dimA = 64, 64, 184, 184, 
    strideA = 2166784, 33856, 184, 1, 
output: TensorDescriptor 0x561083b76120
    type = CUDNN_DATA_HALF
    nbDims = 4
    dimA = 64, 64, 184, 184, 
    strideA = 2166784, 33856, 184, 1, 
weight: FilterDescriptor 0x561084fef0e0
    type = CUDNN_DATA_HALF
    tensor_format = CUDNN_TENSOR_NCHW
    nbDims = 4
    dimA = 64, 64, 1, 1, 
Pointer addresses: 
    input: 0x7f1db0000000
    output: 0x7f1dc0880000
    weight: 0x7f20631f1400

terminate called without an active exception
Aborted (core dumped)
```

## To Reproduce (REQUIRED)

Input:
```
import torch
torch.backends.cuda.matmul.allow_tf32 = True
torch.backends.cudnn.benchmark = True
torch.backends.cudnn.deterministic = False
torch.backends.cudnn.allow_tf32 = True
data = torch.randn([64, 64, 184, 184], dtype=torch.half, device='cuda', requires_grad=True)
net = torch.nn.Conv2d(64, 64, kernel_size=[1, 1], padding=[0, 0], stride=[1, 1], dilation=[1, 1], groups=1)
net = net.cuda().half()
out = net(data)
out.backward(torch.randn_like(out))
torch.cuda.synchronize()
```

## Environment

 - OS: [ Ubuntu 18.04]
 - GPU [e.g. Tesla P100]

**Comment by glenn-jocher** [comment]
@HtutLynn I'm not able to reproduce this in our colab notebook, so it's likely a function of your environment. 
![Screenshot 2020-12-02 at 10 30 40](https://user-images.githubusercontent.com/26833433/100854615-887d2980-3489-11eb-9ba7-feabb989330a.jpg)

I would suggest you try to use one of our verified environments to get started:

## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab Notebook** with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a>
- **Kaggle Notebook** with free GPU: [https://www.kaggle.com/models/ultralytics/yolov5](https://www.kaggle.com/models/ultralytics/yolov5)
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/) 
- **Docker Image** https://hub.docker.com/r/ultralytics/yolov5. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) ![Docker Pulls](https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker)


## Status

![CI CPU testing](https://github.com/ultralytics/yolov5/workflows/CI%20CPU%20testing/badge.svg)

If this badge is green, all [YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions) Continuous Integration (CI) tests are passing. These tests evaluate proper operation of basic YOLOv5 functionality, including training ([train.py](https://github.com/ultralytics/yolov5/blob/master/train.py)), testing ([test.py](https://github.com/ultralytics/yolov5/blob/master/test.py)), inference ([detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py)) and export ([export.py](https://github.com/ultralytics/yolov5/blob/master/models/export.py)) on MacOS, Windows, and Ubuntu.

**Comment by glenn-jocher** [comment]
@HtutLynn also see https://github.com/ultralytics/yolov5/pull/1555 for a PR solution to this problem.

**Comment by glenn-jocher** [comment]
@HtutLynn please try PR https://github.com/ultralytics/yolov5/pull/1555 and confirm that this fixes the problem for you.

**Comment by HtutLynn** [comment]
@glenn-jocher , Sorry for the late reply. I was able to solve this error by setting up the development environment of the VM from starting all over again. I wasn't able to find the root of error the but I definitely think PR #1555 is the case. I really appreciate the help. Thanks!
