### ISSUE TITLE
Training got stuck when I used DistributedDataParallel mode but  dataParallel mode is useful

### ISSUE THREAD

**Issue by wuqi930907** [ultralytics/yolov5#2375]
Hi,I have builded a docker image according to the Dockerfile.
But,my training got stuck with command:“python -m torch.distributed.launch --nproc_per_node 2 train.py --batch-size 32 --data test.yaml --weights pretrained_model/yolov5l.pt”.Following is my log.
![image](https://user-images.githubusercontent.com/34122261/110113342-eead7b80-7ded-11eb-8c46-1a441c4083e7.png)
Although the terminal log has stopped,but the training process still exists.
![image](https://user-images.githubusercontent.com/34122261/110114044-f883ae80-7dee-11eb-95af-5900e508a151.png)
![image](https://user-images.githubusercontent.com/34122261/110113993-e6097500-7dee-11eb-9aa3-f15c93ac76f1.png)

Then, I changed my command:"python train.py --batch-size 32 --data test.yaml --weights pretrained_model/yolov5m.pt --device 0,1", everything is normal.

**Comment by glenn-jocher** [comment]
@wuqi930907 I think in your first command you need to also specify which two devices you are assigning if you use 
`--nproc_per_node 2`

For example you might add --device 0,1 or --device 6,7
```bash
python -m torch.distributed.launch --nproc_per_node 2 train.py --batch-size 32 --data test.yaml --weights pretrained_model/yolov5l.pt --device 0,1
```

**Comment by Finnis** [comment]
I am facing the same problem. The command I used to train is "python -m torch.distributed.launch --nproc_per_node 2 train.py --batch-size 64 --data coco.yaml --cfg yolov5s.yaml --weights '' --device 0,1". But it always stucks at 9 iter. I have 2 2080Ti GPU, pytorch1.8 and python 3.8.8 installed, Nvidia driver version is 460, cuda11.1
![image](https://user-images.githubusercontent.com/26062695/110192551-b6e41980-7e69-11eb-8ddc-accf46526468.png)

**Comment by wuqi930907** [comment]
@glenn-jocher Thank you for your reply，I have added device parameter and changed my command to "python -m torch.distributed.launch --nproc_per_node 2 train.py --batch-size 32 --data test.yaml --weights pretrained_model/yolov5l.pt --device 0,1".However, training still got stuck.

**Comment by glenn-jocher** [comment]
@Finnis @wuqi930907 you should train in a Docker environment if you are having issues with your local environment. See Docker quickstart:


## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab and Kaggle** notebooks with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>


## Status

![CI CPU testing](https://github.com/ultralytics/yolov5/workflows/CI%20CPU%20testing/badge.svg)

If this badge is green, all [YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions) Continuous Integration (CI) tests are passing. These tests evaluate proper operation of basic YOLOv5 functionality, including training ([train.py](https://github.com/ultralytics/yolov5/blob/master/train.py)), testing ([test.py](https://github.com/ultralytics/yolov5/blob/master/test.py)), inference ([detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py)) and export ([export.py](https://github.com/ultralytics/yolov5/blob/master/models/export.py)) on MacOS, Windows, and Ubuntu.

**Comment by roytseng-tw** [comment]
> I am facing the same problem. The command I used to train is "python -m torch.distributed.launch --nproc_per_node 2 train.py --batch-size 64 --data coco.yaml --cfg yolov5s.yaml --weights '' --device 0,1". But it always stucks at 9 iter. I have 2 2080Ti GPU, pytorch1.8 and python 3.8.8 installed, Nvidia driver version is 460, cuda11.1
> ![image](https://user-images.githubusercontent.com/26062695/110192551-b6e41980-7e69-11eb-8ddc-accf46526468.png)

Exactly the same issue here. Can anyone help?

**Comment by glenn-jocher** [comment]
@roytseng-tw @Finnis @wuqi930907 this problem seems to be related to https://github.com/ultralytics/yolov5/issues/2405. @wudashuo found that rolling back to commit a3ecf0fd640465f9a7c009e81bcc5ecabf381004 allowed for proper DDP training. The way to do this would be:

```bash
git clone https://github.com/ultralytics/yolov5 -b a3ecf0fd640465f9a7c009e81bcc5ecabf381004
```
or
```bash
git clone https://github.com/ultralytics/yolov5
git checkout a3ecf0fd640465f9a7c009e81bcc5ecabf381004
```

Alternatively I would highly recommend training DDP in a docker image. We do all of our trainings in Docker images for speed and reproducibility. You can get started with the Docker image here:

- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

**Comment by roytseng-tw** [comment]
@glenn-jocher 
Thanks for your quick reply. ~~I have tried your suggestion but still faced the same issue.~~
Keep figuring out why.

Update:
checkout commit a3ecf0fd640465f9a7c009e81bcc5ecabf381004 fixes the problem

**Comment by glenn-jocher** [comment]
@roytseng-tw which suggestion did you try?

If you believe you have a reproducible issue (happens on a common environment like Docker, on a common dataset like COCO/COCO128/VOC), on unmodified and current master code, then I would recommend filing a complete bug report using the 🐛 **Bug Report template**, providing screenshots and a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us better understand and reproduce the problem. Thank you!

**Comment by wuqi930907** [comment]
@roytseng-tw @glenn-jocher Thanks，I have cloned the latest code and this problem was solved.
