### ISSUE TITLE
RuntimeError: CUDA error: CUBLAS_STATUS_INTERNAL_ERROR when calling `cublasCreate(handle)`

### ISSUE THREAD

**Issue by ghost** [ultralytics/yolov5#2417]
## 🐛 Bug
When I run your code I get the following error:
```
RuntimeError: CUDA error: CUBLAS_STATUS_INTERNAL_ERROR when calling `cublasCreate(handle)`
```
My cuda installation is fine since I am able to run another open-source repository using cuda (the yolact repository).

## To Reproduce (REQUIRED)

Input:
```
python detect.py --source /home/muhammadmehdi/PycharmProjects/VIDEOS/INTERIOR_LENGTHY --weights yolov5s.pt --conf 0.25
```

Output:
```
Traceback (most recent call last):
  File "detect.py", line 175, in <module>
    detect()
  File "detect.py", line 33, in detect
    model = attempt_load(weights, map_location=device)  # load FP32 model
  File "/home/muhammadmehdi/PycharmProjects/SORT_TRIANGULATION/YOLOV5/models/experimental.py", line 120, in attempt_load
    model.append(ckpt['ema' if ckpt.get('ema') else 'model'].float().fuse().eval())  # FP32 model
  File "/home/muhammadmehdi/PycharmProjects/SORT_TRIANGULATION/YOLOV5/models/yolo.py", line 169, in fuse
    m.conv = fuse_conv_and_bn(m.conv, m.bn)  # update conv
  File "/home/muhammadmehdi/PycharmProjects/SORT_TRIANGULATION/YOLOV5/utils/torch_utils.py", line 185, in fuse_conv_and_bn
    fusedconv.weight.copy_(torch.mm(w_bn, w_conv).view(fusedconv.weight.size()))
RuntimeError: CUDA error: CUBLAS_STATUS_INTERNAL_ERROR when calling `cublasCreate(handle)`
```

## Expected behavior
The code should perform inference on the images as outlined in the description here

## Environment

 - OS: [Ubuntu 20.04]
 - GPU [GeForce GTX 1650, 3914.1875MB]

## Additional context
I tried with both conda and pip and both environments encounter the exact same error. My python version is 3.8.5 and torch version is 1.8.0

I also verified that I have the GPU version of pytorch installed by using the following code:
```
print(torch.cuda.current_device())
print(torch.cuda.device(0))
print(torch.cuda.device_count())
print(torch.cuda.get_device_name(0))
print(torch.cuda.is_available())
```
And the output I got was:
```
0
<torch.cuda.device object at 0x7f3664031460>
1
GeForce GTX 1650
True
```

**Comment by glenn-jocher** [comment]
@iAmJuan550 this is an environment issue that may be related to your CUDA/CUDNN or PyTorch installation, and is unrelated to YOLOv5. Please ensure you meet all dependency requirements if you are attempting to run YOLOv5 locally.  If in doubt, create a new virtual Python 3.8 environment, clone the latest repo (**code changes daily**), and `pip install -r requirements.txt` again. We also highly recommend using one of our verified environments below. 


## Requirements

**Python 3.8** or later with all [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) dependencies installed, including **`torch>=1.7`**. To install run:
```bash
$ pip install -r requirements.txt
```


## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab and Kaggle** notebooks with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>


## Status

![CI CPU testing](https://github.com/ultralytics/yolov5/workflows/CI%20CPU%20testing/badge.svg)

If this badge is green, all [YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions) Continuous Integration (CI) tests are passing. These tests evaluate proper operation of basic YOLOv5 functionality, including training ([train.py](https://github.com/ultralytics/yolov5/blob/master/train.py)), testing ([test.py](https://github.com/ultralytics/yolov5/blob/master/test.py)), inference ([detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py)) and export ([export.py](https://github.com/ultralytics/yolov5/blob/master/models/export.py)) on MacOS, Windows, and Ubuntu.

**Comment by ghost** [comment]
I fixed this problem by downgrading from torch 1.8.0 to 1.7.0
I also downgraded the torchvision version from 0.9.0 to 0.8.1 (this solves the NMS not available with CUDA backend issue)

**Comment by vinhtran1** [comment]
> I fixed this problem by downgrading from torch 1.8.0 to 1.7.0
> I also downgraded the torchvision version from 0.9.0 to 0.8.1 (this solves the NMS not available with CUDA backend issue)

I worked for me, thank you
