### ISSUE TITLE
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED

### ISSUE THREAD

**Issue by joel5638** [ultralytics/yolov5#2542]
I'm trying to train a model with just 40 images in train and 10 in valid.

I get this CUDNN error... please help.. I'm training with this command:

**python3 train.py --epochs 200 --batch-size 4 --data /home/AD/skanneboina/Workbench/yolov5/data/tomato.yaml --device 0,1**
![Screenshot from 2021-03-21 17-25-46](https://user-images.githubusercontent.com/38422983/111903996-940d5400-8a6a-11eb-8c8e-876a800305f0.png)

**Comment by joel5638** [comment]
I did install requirements and pulled the latest rep..nothing works.. I still get that error.

@glenn-jocher can you help me

**Comment by michaeldemos** [comment]
Hi I am getting the same error

%%time
!python train.py --img 416 --batch 16 --epochs 400 --data '../data.yaml' --cfg ./models/yolov5x.yaml --weights '' --name yolov5x_results --nosave --cache

![image](https://user-images.githubusercontent.com/29190906/111926461-029cf100-8b01-11eb-808a-854bbbd3fd80.png)

**Comment by danhuit** [comment]
[https://stackoverflow.com/questions/66528261/training-yolov5-causes-a-cudnn-status-not-initialized-error](Install torch and tourchvision use conda)

**Comment by danhuit** [comment]
[Install torch and tourchvision use conda](https://stackoverflow.com/questions/66528261/training-yolov5-causes-a-cudnn-status-not-initialized-error)

**Comment by glenn-jocher** [comment]
@joel5638 @danhuit this may be due to your CUDA/CUDNN install. We don't have resources to help debug specific user environments, but I can point you to our verified working environments below. If you are trying to train locally Docker is a great option, as it includes it's own verified working environment:

Please ensure you meet all dependency requirements if you are attempting to run YOLOv5 locally.  If in doubt, create a new virtual Python 3.8 environment, clone the latest repo (**code changes daily**), and `pip install -r requirements.txt` again. We also highly recommend using one of our verified environments below. 


## Requirements

**Python 3.8** or later with all [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) dependencies installed, including **`torch>=1.7`**. To install run:
```bash
$ pip install -r requirements.txt
```


## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab and Kaggle** notebooks with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>


## Status

![CI CPU testing](https://github.com/ultralytics/yolov5/workflows/CI%20CPU%20testing/badge.svg)

If this badge is green, all [YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions) Continuous Integration (CI) tests are passing. These tests evaluate proper operation of basic YOLOv5 functionality, including training ([train.py](https://github.com/ultralytics/yolov5/blob/master/train.py)), testing ([test.py](https://github.com/ultralytics/yolov5/blob/master/test.py)), inference ([detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py)) and export ([export.py](https://github.com/ultralytics/yolov5/blob/master/models/export.py)) on MacOS, Windows, and Ubuntu.

**Comment by mkutu** [comment]
@aviez

> Hi @joel5638 .
> This issue is related to TORCH not the Yolov5.
> I have been facing this issue some days ago.
> 
> The solution is to downgrade the torch & torchvision.
> 
> Use
> 
> ```
> pip install torch==1.7.1 torchvision==0.8.2
> ```
> 
> instead of torch & torchvision from requirements.txt.
> 
> And it works also on Python 3.6.9 and Python 3.7.10

This worked for me as well.

**Comment by hdnh2006** [comment]
> Hi @joel5638 .
> This issue is related to TORCH not the Yolov5.
> I have been facing this issue some days ago.
> 
> The solution is to downgrade the torch & torchvision.
> 
> Use
> 
> ```
> pip install torch==1.7.1 torchvision==0.8.2
> ```
> 
> instead of torch & torchvision from requirements.txt.
> 
> And it works also on Python 3.6.9 and Python 3.7.10

I made the opposite, I updated from torch 1.8 to torch 1.9 and it worked! It seems it is a bug of torch 1.8 I hope this information could help somebody.
