### ISSUE TITLE
CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by leeyunhome** [ultralytics/yolov5#2855]
## ❔Question

Hello?

I'm using rtx3080.
I have encountered below messages when I run detect.py
Can you tell me how to resolve this problem?

Namespace(agnostic_nms=False, augment=False, classes=None, conf_thres=0.25, device='', exist_ok=False, img_size=640, iou_thres=0.45, name='exp', nosave=False, project='runs/detect', save_conf=False, save_txt=False, source='data/images', update=False, view_img=False, weights=['yolov5s.pt'])
/home/aiserver/anaconda3/envs/py37/lib/python3.7/site-packages/torch/cuda/__init__.py:104: UserWarning: 
NVIDIA GeForce RTX 3080 with CUDA capability sm_86 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70.
If you want to use the NVIDIA GeForce RTX 3080 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
YOLOv5 🚀 v5.0-14-g238583b torch 1.8.1+cu102 CUDA:0 (NVIDIA GeForce RTX 3080, 10016.75MB)

Traceback (most recent call last):
  File "detect.py", line 178, in <module>
    detect()
  File "detect.py", line 34, in detect
    model = attempt_load(weights, map_location=device)  # load FP32 model
  File "/home/aiserver/coding/GitHub/yolov5/models/experimental.py", line 119, in attempt_load
    model.append(ckpt['ema' if ckpt.get('ema') else 'model'].float().fuse().eval())  # FP32 model
  File "/home/aiserver/anaconda3/envs/py37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 534, in float
    return self._apply(lambda t: t.float() if t.is_floating_point() else t)
  File "/home/aiserver/anaconda3/envs/py37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/home/aiserver/anaconda3/envs/py37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/home/aiserver/anaconda3/envs/py37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "/home/aiserver/anaconda3/envs/py37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 409, in _apply
    param_applied = fn(param)
  File "/home/aiserver/anaconda3/envs/py37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 534, in <lambda>
    return self._apply(lambda t: t.float() if t.is_floating_point() else t)
RuntimeError: CUDA error: no kernel image is available for execution on the device

**Comment by glenn-jocher** [comment]
@leeyunhome seems like your CUDA and PyTorch installations are not compatible per the UserWarning you show:

> UserWarning: 
> NVIDIA GeForce RTX 3080 with CUDA capability sm_86 is not compatible with the current PyTorch installation.
> The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70.
> If you want to use the NVIDIA GeForce RTX 3080 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

**Comment by aviezab** [comment]
You can use this wheel I have tried with our RTX 3XXX series
Download those, and install with `pip`
https://download.pytorch.org/whl/cu111/torch-1.8.1%2Bcu111-cp39-cp39-linux_x86_64.whl
and this is the torchvision as well 
https://download.pytorch.org/whl/cu111/torchvision-0.9.1%2Bcu111-cp39-cp39-linux_x86_64.whl

That is for Python 3.9 and CUDA 11.

@leeyunhome

**Comment by Muyiyunzi** [comment]
I solved this using 'conda install' provided by the PyTorch official website here:
`conda install pytorch torchvision cudatoolkit=11.1 -c pytorch -c conda-forge`
my env is RTX 3070 and it should've worked for any other RTX 30XX series.

(btw I manually installed CUDA 10.2 before(if using `nvcc -V` It's still showing CUDA 10.2) but it doesn't matter, I guess that's the power of conda shell^_^)

**Comment by aviezab** [comment]
Good job @Muyiyunzi 
But I prefer using without conda, because simple (ofc simple for deployment too).

Yes CUDA library is also installed when using torch so no problem if have different CUDA lib installed.

**Comment by AayushAgrawal2003** [comment]
Try building PyTorch from the source rather than the requirements file. This worked for me.

[PyTorch Installation](https://pytorch.org/get-started/previous-versions/)

# ROCM 5.1.1 (Linux only)
pip install torch==1.12.0+rocm5.1.1 torchvision==0.13.0+rocm5.1.1 torchaudio==0.12.0 --extra-index-url  https://download.pytorch.org/whl/rocm5.1.1
# CUDA 11.6
pip install torch==1.12.0+cu116 torchvision==0.13.0+cu116 torchaudio==0.12.0 --extra-index-url https://download.pytorch.org/whl/cu116
# CUDA 11.3
pip install torch==1.12.0+cu113 torchvision==0.13.0+cu113 torchaudio==0.12.0 --extra-index-url https://download.pytorch.org/whl/cu113
# CUDA 10.2
pip install torch==1.12.0+cu102 torchvision==0.13.0+cu102 torchaudio==0.12.0 --extra-index-url https://download.pytorch.org/whl/cu102
# CPU only
pip install torch==1.12.0+cpu torchvision==0.13.0+cpu torchaudio==0.12.0 --extra-index-url https://download.pytorch.org/whl/cpu
Download based on CUDA version

nvcc --version #To check CUDA version

**Comment by glenn-jocher** [comment]
Thanks for sharing your solution, @AayushAgrawal2003. You've made a great point about the simplicity of using environments without conda. Your method using pip for installation is a helpful alternative for many users. Good luck with your implementation!
