### ISSUE TITLE
Error on Cuda-11.x

### ISSUE THREAD

**Issue by nocolour** [ultralytics/yolov5#3011]
I found out when running with cuda, it was error. Anyone can run on ubuntu 20.04.2 with cuda-11.1 or 11.2 or 11.3 without error? I think maybe only can run cuda-10.2 under ubuntu 18.04 without error.
![cuda_error](https://user-images.githubusercontent.com/6244952/116798531-ed18df00-ab22-11eb-8481-106f32c70783.png)

**Comment by iceisfun** [comment]
Working fine, I had an issue a long time ago using a old gpu and just went straight to a rtx titan on my dev machine, not sure about the gt 710.

All I use now is rtx titan, a100 and rtx 3090, I have tested some on gtx 1080 and gtx 1080 ti

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  A100-SXM4-40GB      On   | 00000000:01:00.0 Off |                    0 |

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"

**Comment by nocolour** [comment]
Can u check, are you running with CPU mode or CUDA mode? I tested Cuda-11.1, 11.2 and 11.3 download from nvidia, when running in GPU (CUDA MODE) error happen. 
![cuda_error1](https://user-images.githubusercontent.com/6244952/116806905-9cc17180-ab62-11eb-84b2-99b1c5b85dbe.png)

**Comment by iceisfun** [comment]
We are running in cuda mode, we monitor gpu usage on all servers. Our versions are a little different, if I upgraded to current I'm sure it would also work.

At some point we had to upgrade or driver version and pytorch version when the 3090/a100 cards came out


Namespace(agnostic_nms=False, augment=False, classes=None, conf_thres=0.25, device='', exist_ok=False, img_size=640, iou_thres=0.45, name='exp', project='runs/detect', save_conf=False, save_txt=False, source='./data/images/bus.jpg', update=False, view_img=False, weights='yolov5s.pt')
YOLOv5 v4.0-124-gc51dfec torch 1.8.0a0+52ea372 CUDA:0 (A100-SXM4-40GB, 40536.1875MB)
                                               CUDA:1 (A100-SXM4-40GB, 40536.1875MB)
                                               CUDA:2 (A100-SXM4-40GB, 40536.1875MB)
                                               CUDA:3 (A100-SXM4-40GB, 40536.1875MB)

Fusing layers... 
Model Summary: 224 layers, 7266973 parameters, 0 gradients, 17.0 GFLOPS
image 1/1 /usr/src/app/data/images/bus.jpg: 640x480 4 persons, 1 bus, Done. (0.037s)
Results saved to runs/detect/exp
Done. (0.163s)


EDIT

Its also worth noting we run in docker containers with a custom Dockerfile to build from pytorch and clone yolov5 from github

**Comment by iceisfun** [comment]
Could you try this Dockerfile

You will also need docker and nvidia-container-toolkit for this example
```
curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add -
curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list
apt-get update && sudo apt-get install -y nvidia-container-toolkit
```

```
FROM nvcr.io/nvidia/pytorch:21.02-py3

ENV PYTHONUNBUFFERED 1
ENV DEBIAN_FRONTEND noninteractive

RUN apt update && rm /var/lib/dpkg/statoverride && apt-get install -y libgl1-mesa-glx libgl1-mesa-dev

RUN git clone https://github.com/ultralytics/yolov5.git /usr/src/app

WORKDIR /usr/src/app
RUN pip3 install -r requirements.txt

RUN python3 -c "from utils.google_utils import attempt_download; \
attempt_download('weights/yolov5s.pt'); \
attempt_download('weights/yolov5m.pt'); \
attempt_download('weights/yolov5x.pt'); \
attempt_download('weights/yolov5l.pt')" && cp weights/*.pt .

ENTRYPOINT [ "python3", "detect.py", "--source", "./data/images/bus.jpg" ]
#ENTRYPOINT [ "/bin/sh"]
```



Then run

```
docker build -t test .

docker run --rm -it --ipc=host --gpus all -v /sys:/sys test
```
You should get output similar to

```
Namespace(agnostic_nms=False, augment=False, classes=None, conf_thres=0.25, device='', exist_ok=False, hide_conf=False, hide_labels=False, img_size=640, iou_thres=0.45, line_thickness=3, name='exp', nosave=False, project='runs/detect', save_conf=False, save_crop=False, save_txt=False, source='./data/images/bus.jpg', update=False, view_img=False, weights='yolov5s.pt')
YOLOv5 🚀 v5.0-59-g31ee54c torch 1.8.0a0+52ea372 CUDA:0 (TITAN RTX, 24220.3125MB)
                                                CUDA:1 (TITAN RTX, 24220.3125MB)
                                                CUDA:2 (TITAN RTX, 24220.3125MB)

Fusing layers... 
Model Summary: 224 layers, 7266973 parameters, 0 gradients
image 1/1 /usr/src/app/data/images/bus.jpg: 640x480 4 persons, 1 bus, 1 fire hydrant, Done. (0.016s)
Results saved to runs/detect/exp
Done. (0.041s)
```

**Comment by nocolour** [comment]
> Could you try this Dockerfile
> 
> You will also need docker and nvidia-container-toolkit for this example
> 
> ```
> curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add -
> curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list
> apt-get update && sudo apt-get install -y nvidia-container-toolkit
> ```
> 
> ```
> FROM nvcr.io/nvidia/pytorch:21.02-py3
> 
> ENV PYTHONUNBUFFERED 1
> ENV DEBIAN_FRONTEND noninteractive
> 
> RUN apt update && rm /var/lib/dpkg/statoverride && apt-get install -y libgl1-mesa-glx libgl1-mesa-dev
> 
> RUN git clone https://github.com/ultralytics/yolov5.git /usr/src/app
> 
> WORKDIR /usr/src/app
> RUN pip3 install -r requirements.txt
> 
> RUN python3 -c "from utils.google_utils import attempt_download; \
> attempt_download('weights/yolov5s.pt'); \
> attempt_download('weights/yolov5m.pt'); \
> attempt_download('weights/yolov5x.pt'); \
> attempt_download('weights/yolov5l.pt')" && cp weights/*.pt .
> 
> ENTRYPOINT [ "python3", "detect.py", "--source", "./data/images/bus.jpg" ]
> #ENTRYPOINT [ "/bin/sh"]
> ```
> 
> Then run
> 
> ```
> docker build -t test .
> 
> docker run --rm -it --ipc=host --gpus all -v /sys:/sys test
> ```
> 
> You should get output similar to
> 
> ```
> Namespace(agnostic_nms=False, augment=False, classes=None, conf_thres=0.25, device='', exist_ok=False, hide_conf=False, hide_labels=False, img_size=640, iou_thres=0.45, line_thickness=3, name='exp', nosave=False, project='runs/detect', save_conf=False, save_crop=False, save_txt=False, source='./data/images/bus.jpg', update=False, view_img=False, weights='yolov5s.pt')
> YOLOv5 🚀 v5.0-59-g31ee54c torch 1.8.0a0+52ea372 CUDA:0 (TITAN RTX, 24220.3125MB)
>                                                 CUDA:1 (TITAN RTX, 24220.3125MB)
>                                                 CUDA:2 (TITAN RTX, 24220.3125MB)
> 
> Fusing layers... 
> Model Summary: 224 layers, 7266973 parameters, 0 gradients
> image 1/1 /usr/src/app/data/images/bus.jpg: 640x480 4 persons, 1 bus, 1 fire hydrant, Done. (0.016s)
> Results saved to runs/detect/exp
> Done. (0.041s)
> ```

Thank you.
Later, I try again.

**Comment by nocolour** [comment]
I think Cuda error caused by GPU type. Cuda 11.x need nvidia GPU with compute capability 3.5 and above.
GT710 cuda compute capability is 2.1. It's below 3.5.
Now hard to get new GPU card. I will test again with other nvidia card with compute capability 6.1. I think it should be working.

**Comment by nocolour** [comment]
Problem solved with compute capability 6.1 GPU card (GTX1050TI).
can close case
