### ISSUE TITLE
Custom Dataset Training

### ISSUE THREAD

**Issue by rafcy** [ultralytics/yolov5#311]
Hey guys,
i've been trying to train yolov5m using a  dataset of my own. It is my first time using pytorch so i just followed all the steps in the 'how to train tutorial'. My initial labels were in darknet format (class,topLx,topLy,w,h) so i've changed all labels to "class,xcntr,ycntr,w,h" as well.  While the first epoch ends i get the following error when it tries to do the MAP calculations (as far as i am comprehending).  From a research on the internet i have found that the error seems to be coming from the data-labels 
but i can't find any error on the labels.

The error is this one :
`/opt/conda/conda-bld/pytorch_1591914880026/work/aten/src/ATen/native/cuda/IndexKernel.cu:60: operator(): block: [6,0,0], thread: [24,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1591914880026/work/aten/src/ATen/native/cuda/IndexKernel.cu:60: operator(): block: [6,0,0], thread: [25,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1591914880026/work/aten/src/ATen/native/cuda/IndexKernel.cu:60: operator(): block: [6,0,0], thread: [26,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
               Class      Images     Targets           P           R      mAP@.5  mAP@.5:.95:   4%|██                                             | 4/93 [00:05<01:57,  1.32s/it]
Traceback (most recent call last):
  File "train.py", line 394, in <module>
    train(hyp)
  File "train.py", line 299, in train
    dataloader=testloader)
  File "/3TBdisk/rmakri01/yolov5/test.py", line 93, in test
    loss += compute_loss([x.float() for x in train_out], targets, model)[1][:3]  # GIoU, obj, cls
  File "/3TBdisk/rmakri01/yolov5/utils/utils.py", line 460, in compute_loss
    tobj[b, a, gj, gi] = (1.0 - model.gr) + model.gr * giou.detach().clamp(0).type(tobj.dtype)  # giou ratio
RuntimeError: CUDA error: device-side assert triggered `

PS. I am training using batch 14, yolov5m model, no initial weights, 5k train - 1k test images.

**Comment by glenn-jocher** [comment]
@rafcy start from the tutorial in a working environment:
https://docs.ultralytics.com/yolov5/tutorials/train_custom_data

## Reproduce Our Environment

To access an up-to-date working environment (with all dependencies including CUDA/CUDNN, Python and PyTorch preinstalled), consider a:

- **GCP** Deep Learning VM with $300 free credit offer: See our [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/) 
- **Google Colab Notebook** with 12 hours of free GPU time. <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a>
- **Docker Image** https://hub.docker.com/r/ultralytics/yolov5. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) ![Docker Pulls](https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker)

**Comment by rafcy** [comment]
> @rafcy start from the tutorial in a working environment:
> https://docs.ultralytics.com/yolov5/tutorials/train_custom_data
> 
> ## Reproduce Our Environment
> To access an up-to-date working environment (with all dependencies including CUDA/CUDNN, Python and PyTorch preinstalled), consider a:
> 
> * **GCP** Deep Learning VM with $300 free credit offer: See our [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
> * **Google Colab Notebook** with 12 hours of free GPU time. [![Open In Colab](https://camo.githubusercontent.com/52feade06f2fecbf006889a904d221e6a730c194/68747470733a2f2f636f6c61622e72657365617263682e676f6f676c652e636f6d2f6173736574732f636f6c61622d62616467652e737667)](https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb)
> * **Docker Image** https://hub.docker.com/r/ultralytics/yolov5. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) ![Docker Pulls](https://camo.githubusercontent.com/caa63570e9f4e9771b02fc86d87e78aad3bf9785/68747470733a2f2f696d672e736869656c64732e696f2f646f636b65722f70756c6c732f756c7472616c79746963732f796f6c6f76353f6c6f676f3d646f636b6572)

but this is the exact tutorial i was following

**Comment by glenn-jocher** [comment]
@rafcy then you have an environment issue, use a working environment.

**Comment by rafcy** [comment]
> @rafcy then you have an environment issue, use a working environment.
ok then, i will give that a try and get back to you! Thank u!

**Comment by glenn-jocher** [comment]
@rafcy you're welcome! I would try the colab notebook, it's the easiest way to get started. If you are in China the docker will work, and the kaggle notebook may also work there, not sure.

**Comment by glenn-jocher** [comment]
Actually roboflow also has a good tutorial on getting started too https://blog.roboflow.ai/how-to-train-yolov5-on-a-custom-dataset/

**Comment by rafcy** [comment]
thank you for your suggestions but i am stubborn so i am still trying to figure out the problem. I reinstalled the environment's requirements and tried both yolov5,yolov3 git repositories and they both gave an error on the MAP calculation. Is this a generic error or can i somehow specify what or where the problem is?

**Comment by glenn-jocher** [comment]
@rafcy you probably have a dataset or data labelling problem. I've made a lot of updates even just yesterday, so I would do this:

0. start from the colab notebook so you have a verified environment
1. run the setup, which git clones a fresh copy of yolov5, so you have the latest
2. train coco128 and see that it works
3. train your dataset, and examine your train*.jpg and test*.jpg to validate your labels

**Comment by imyhxy** [comment]
> @rafcy you probably have a dataset or data labelling problem. I've made a lot of updates even just yesterday, so I would do this:
> 
> 1. start from the colab notebook so you have a verified environment
> 2. run the setup, which git clones a fresh copy of yolov5, so you have the latest
> 3. train coco128 and see that it works
> 4. train your dataset, and examine your train*.jpg and test*.jpg to validate your labels

what is the coco128?

**Comment by rafcy** [comment]
So i did some tests based on your suggestions. I tried to train a different dataset that i have and the train went smoothly, so my environment works  fine. So after that i tried to find the problematic batch of images/labels from my dataset by printing the batch filenames from the test.py file. Then i removed them from the dataset and now the training works!! Still can't figure out what's the problem with that set of data though.. oh well!

**Comment by Ramarjohn** [comment]
Hello rafcy@ and @glenn-jocher I have some problem ,how to fix that solutions.i will give my error in image 
![20200718_204659](https://user-images.githubusercontent.com/47788261/87913313-8000f500-ca8c-11ea-9b41-ad4c042d6fb5.jpg)this error will show .but I am using google colab notebook.plese help to solve this proproblem

**Comment by Ramarjohn** [comment]
> Hello rafcy@ and @glenn-jocher I have some problem ,how to fix that solutions.i will give my error in image
> ![20200718_204659](https://user-images.githubusercontent.com/47788261/87913313-8000f500-ca8c-11ea-9b41-ad4c042d6fb5.jpg)this error will show .but I am using google colab notebook.plese help to solve this proproblem

**Comment by rafcy** [comment]
> Hello rafcy@ and @glenn-jocher I have some problem ,how to fix that solutions.i will give my error in image 
> ![20200718_204659](https://user-images.githubusercontent.com/47788261/87913313-8000f500-ca8c-11ea-9b41-ad4c042d6fb5.jpg)this error will show .but I am using google colab notebook.plese help to solve this proproblem 
> 

It is an error in your dataset. What i did to find the problem was to add a print(paths) in line 72 (inside the for loop) in order to find the problematic batch images. At first just remove them to see if you get it working and then try to figure out if the imgs are corrupted or if u have wrong label info in the txt files.

**Comment by Ramarjohn** [comment]
tank you @rafcy 
but i need some clarifications about dataset in yolov5. i have to use the my dataset it gives  error like that before i mentioned .but i have to uploads the some dataset in raboflow   to create the similar dataset ,the model file is generated. but still i did not know  about behind the process of raboflow .please to give the some solution...clearly

**Comment by donghyeops** [comment]
Hi
I had same error.
When I load my dataset, I clipped all bounding boxes to 0 to 1 using following code in datasets.py/__init__()
```
for i in range(len(self.labels)):
    l = np.array(self.labels[i], dtype=np.float32)

    l[(l < 0)] = 0  # [0, -]

    ti = l > 1
    ti[:, 0] = False
    l[ti] = 1  # [0, 1]

    self.labels[i] = l
```
But the error was happened at specific epoch in test time.
I just edited boundary [0,1] to [0.001, 0.999] and it worked well.

```
for i in range(len(self.labels)):
    l = np.array(self.labels[i], dtype=np.float32)

    l[(l <= 0)] = 0.001  # [0.001, -]

    ti = l >= 1
    ti[:, 0] = False
    l[ti] = 0.999  # [0.001, 0.999]

    self.labels[i] = l
```
I don't know why this solves the problem.
But, I hope this to help you.

**Comment by GWwangshuo** [comment]
> tank you @rafcy
> but i need some clarifications about dataset in yolov5. i have to use the my dataset it gives error like that before i mentioned .but i have to uploads the some dataset in raboflow to create the similar dataset ,the model file is generated. but still i did not know about behind the process of raboflow .please to give the some solution...clearly

Have you found some solutions? I encountered exactly the same problem. I have carefully checked my annotation and quite sure there are no negative values.

**Comment by rafcy** [comment]
> Hi
> I had same error.
> When I load my dataset, I clipped all bounding boxes to 0 to 1 using following code in datasets.py/**init**()
> 
> ```
> for i in range(len(self.labels)):
>     l = np.array(self.labels[i], dtype=np.float32)
> 
>     l[(l < 0)] = 0  # [0, -]
> 
>     ti = l > 1
>     ti[:, 0] = False
>     l[ti] = 1  # [0, 1]
> 
>     self.labels[i] = l
> ```
> 
> But the error was happened at specific epoch in test time.
> I just edited boundary [0,1] to [0.001, 0.999] and it worked well.
> 
> ```
> for i in range(len(self.labels)):
>     l = np.array(self.labels[i], dtype=np.float32)
> 
>     l[(l <= 0)] = 0.001  # [0.001, -]
> 
>     ti = l >= 1
>     ti[:, 0] = False
>     l[ti] = 0.999  # [0.001, 0.999]
> 
>     self.labels[i] = l
> ```
> 
> I don't know why this solves the problem.
> But, I hope this to help you.

that's probably because this repository doesn't has any error checking on the labels. This means that whenever there is an error with the labels we have no clue if the problem is with the x,y boundaries, the image or the class. Also, a small fix should be to integrate the code you wrote by default in this repository when loading the labels.

> > tank you @rafcy
> > but i need some clarifications about dataset in yolov5. i have to use the my dataset it gives error like that before i mentioned .but i have to uploads the some dataset in raboflow to create the similar dataset ,the model file is generated. but still i did not know about behind the process of raboflow .please to give the some solution...clearly
> 
> Have you found some solutions? I encountered exactly the same problem. I have carefully checked my annotation and quite sure there are no negative values.

Not really, i have used another repository for pytorch-darknet and it is working using the same dataset. The problem is mostly based on the dataset though, some checks need to be added for the x,y boundaries.

**Comment by GWwangshuo** [comment]
@rafcy Thanks for your quick reply. Could you please tell me which repo of 'pytorch-darknet' you use? Thanks again.

**Comment by rafcy** [comment]
> @rafcy Thanks for your quick reply. Could you please tell me which repo of 'pytorch-darknet' you use? Thanks again.

I have sent you an email.

**Comment by GWwangshuo** [comment]
> pytorch-darknet

Thanks a lot. I have carefully checked my gmail and sure I do not receive it. Could you please send it to `gw.wangshuo@gmail.com ` again. Sorry for the inconvenience.

**Comment by glenn-jocher** [comment]
@rafcy @GWwangshuo we do error checking on the labels as part of the dataloader initialization. If you wanted to add additional checks this would be the place:
https://github.com/ultralytics/yolov5/blob/5e0b90de8f7782b3803fa2886bb824c2336358d0/utils/datasets.py#L379-L391

We also do error checking on the images themselves when creating a *.cache file the first time a dataset is used (and anytime it is modified). This is another place you could add additional error checks.
https://github.com/ultralytics/yolov5/blob/5e0b90de8f7782b3803fa2886bb824c2336358d0/utils/datasets.py#L445-L466

**Comment by GWwangshuo** [comment]
@glenn-jocher Thanks for your reply. I returned back to check the annotations and found similar problems with @sdh9446 . Although no negative values found in the annotations, there are some 0 and 1 values which is the cause of the problem.  Since @sdh9446 's solution does not work for me. I rewrite the `Label Create Function` for training custom data and make sure the `normalized xywh` is in `(0, 1)` rather than `[0, 1]`.

**Comment by NaimaRasheed** [comment]
![Screenshot from 2021-02-23 13-51-55](https://user-images.githubusercontent.com/75273293/108853777-09f2dc80-75df-11eb-9969-0e9bb78ff018.png)
 please help me getting this error!! although it put the labels and images in regarding folder also put the right path in the coco file

**Comment by glenn-jocher** [comment]
@NaimaRasheed your dataset could not be found. Follow the directions in the tutorial for dataset creation:

## Tutorials

* [Train Custom Data](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data)&nbsp; 🚀 RECOMMENDED

**Comment by NaimaRasheed** [comment]
@glenn-jocher I followed the tutorial, but I'm unable to understand why I'm facing this error. I placed images in images folders, same did with labels, also made changes in coco128.yaml. but still facing this error.!!

**Comment by glenn-jocher** [comment]
@NaimaRasheed organize your data according to the tutorial, and use coco128 as an example. You can train coco128 in 1 click using the colab notebook if that helps:

- **Google Colab and Kaggle** notebooks with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>

**Comment by NaimaRasheed** [comment]
@glenn-jocher I downloaded the data set and replaced it with my custom, now getting this error
![Screenshot from 2021-02-24 09-17-16](https://user-images.githubusercontent.com/75273293/108978267-57c02100-7681-11eb-9f16-53aa8ba86ae4.png)

**Comment by NaimaRasheed** [comment]
@glenn-jocher 
![Screenshot from 2021-02-24 11-16-30](https://user-images.githubusercontent.com/75273293/108993008-e177ea80-7691-11eb-9271-33517b6b494d.png)

 getting this error although i run it on my local machine

**Comment by glenn-jocher** [comment]
@NaimaRasheed dataloader workers are killed when your hardware lacks sufficient resources (cpus, ram) for the tasks you've requested.

**Comment by NaimaRasheed** [comment]
@glenn-jocher  yeah all sorted with training!! thanks alot, but one more problem I trained the yolov5s with my custom dataset, when I run the detect.py(with my custom dataset training weight) it didn't detect any object on images. the objects in resultant images remain undetected.

**Comment by glenn-jocher** [comment]
@NaimaRasheed if no objects are detected by detect.py then your trained model is not capable of detecting objects in your images at your supplied thresholds.
