### ISSUE TITLE
cuda torch yolov5 compatibility issue

### ISSUE THREAD

**Issue by lleye** [ultralytics/yolov5#3360]
Getting RuntimeError: CUDA error: no kernel image is available for execution on the device.
cuda 11.0, torch 1.8.1 
v4.0-126-g886f1c0 torch 1.8.1+cu102

`pip show torch
`
Name: torch
Version: 1.8.1
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3
Location: /home/poyn/miniconda3/envs/custommodel/lib/python3.8/site-packages
Requires: numpy, typing-extensions
Required-by: torchvision, thop

`print('Setup complete. Using torch %s %s' % (torch.version, torch.cuda.get_device_properties(0) if torch.cuda.is_available() else 'CPU'))`
A100-SXM4-40GB with CUDA capability sm_80 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70.
If you want to use the A100-SXM4-40GB GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
Setup complete. Using torch <module 'torch.version' from '/home/poyn/miniconda3/envs/custommodel/lib/python3.8/site-packages/torch/version.py'> _CudaDeviceProperties(name='A100-SXM4-40GB', major=8, minor=0, total_memory=40537MB, multi_processor_count=108)

doing `conda install pytorch torchvision torchaudio cudatoolkit=11.1 -c pytorch -c nvidia
` from pytorch.org doesnt fix it

@ iceisfun @glenn-jocher please advice

**Comment by nocolour** [comment]
Hi,
For Cuda 11.1, 11.2, 11.3; You can try torch+cu111:
pip install torch==1.8.1+cu111 torchvision==0.9.1+cu111 -f https://download.pytorch.org/whl/torch_stable.html

Cuda compute capability must 3.5 or above for torch 1.8.1 to work with CUDA
CuDnn is needed
Make sure your path for cuda was set and correct.

**Comment by lleye** [comment]
thanks @nocolour works now

**Comment by DBadLuck** [comment]
@lleye which --batch-size did you use? I was facing the same problem with Multi-GPU DDP training.

**Comment by lleye** [comment]
@DBadLuck  i just used @nocolour suggestion `For Cuda 11.1, 11.2, 11.3; You can try torch+cu111:
pip install torch==1.8.1+cu111 torchvision==0.9.1+cu111 -f https://download.pytorch.org/whl/torch_stable.html` and that solved the issue. batch size didnt matter, you only have to make sure its a multiple of your gpu number e.g. if you have 4 gpu, batch size has to be multiples of 4

**Comment by glenn-jocher** [comment]
@lleye yes that's correct. GPU count multiplicity is asserted here:
https://github.com/ultralytics/yolov5/blob/b6fdd2e5e54aa3464b360fe6d9c6f3cb216f3778/utils/torch_utils.py#L77-L78
