### ISSUE TITLE
Inconsistent CUDA is out of memory runtime error on V100

### ISSUE THREAD

**Issue by JanErikDoornweerd** [ultralytics/yolov5#4872]
## ❔Question

Hi! Thank you for making yolo more accessible! 

I am training multiple models, but I am sometimes running out of memory while I did not change anything.
Most settings are default except for batch (=8) and image size (=1920).

Training is done on a V100 on a HPC, so VRAM should not be an issue, or so I thought.  

I have successfully completed a full run, as in, trained and tested a small model with batch 8 and img-size 1920. However, most recent train sessions are eliminated due to exceeding the memory limit (VRAM -16GB). Sometimes a job can be cancelled as early as the 26th epoch, while other runs can run to the 157th epoch.

Once, I even got 'Unable to find a valid cuDNN algorithm to run convolution', which according [to SO](https://stackoverflow.com/questions/61467751/unable-to-find-a-valid-cudnn-algorithm-to-run-convolution) happens when you exceed the memory limit.

## Additional context
Dataset size is max. 500 frames.
Console output tells me I am using 15.3 VRAM.

## Tried solutions
Reduce --batch-size  **16 -> 8**
Reduce --img-size                                                                                    **1920 -> Detecting small objects**
Reduce model size                                                                                    **YOLOv5s**
Train with multi-GPU at the same --batch-size                                         **Not wanted due to job load**
Upgrade your hardware to a larger GPU                                                  **Already at V100**
Train on free GPU backends with up to 16GB of CUDA memory              **Already at V100**

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.57.02    Driver Version: 470.57.02    CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  Off  | 00000000:1A:00.0 Off |                    0 |
| N/A   52C    P0    63W / 300W |  15900MiB / 16160MiB |      1%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-SXM2...  Off  | 00000000:1C:00.0 Off |                    0 |
| N/A   38C    P0    55W / 300W |      0MiB / 16160MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  Tesla V100-SXM2...  Off  | 00000000:1D:00.0 Off |                    0 |
| N/A   40C    P0    59W / 300W |      0MiB / 16160MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  Tesla V100-SXM2...  Off  | 00000000:1E:00.0 Off |                    0 |
| N/A   43C    P0    60W / 300W |      0MiB / 16160MiB |      2%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A     21630      C   python3                         15891MiB |
+-----------------------------------------------------------------------------+
```

**Comment by glenn-jocher** [comment]
@TheCrafft it seems like you are training at the borderline for CUDA OOM, you should simply reduce your batch size to a safer level, i.e. --batch 7 or --batch 6.

For the most accurate reading on CUDA utilization you can also use `nvidia-smi`.

**Comment by JanErikDoornweerd** [comment]
@glenn-jocher I was afraid so, but the problems keeps occurring even when lowering --batch-size. 
At --batch-size 7 -15.3 VRAM
At --batch-size 6 -11 VRAM
At --batch-size 5 -9.15 VRAM
At --batch-size 4  -7.75 VRAM

Could a process suddenly cause a spike in VRAM usage?

**Comment by glenn-jocher** [comment]
@TheCrafft there are no known memory issues currently. I would restart your machine and train normally at about 80% of your card's capacity. This is what our internal trainings look like:

<img width="1465" alt="Screen Shot 2021-09-21 at 5 14 58 PM" src="https://user-images.githubusercontent.com/26833433/134198222-03ababeb-9304-4ebe-9860-df00d5b5c9c1.png">

**Comment by JanErikDoornweerd** [comment]
@glenn-jocher 
Thank you! I will investigate further and update this issue once I have a solution.

**Comment by JanErikDoornweerd** [comment]
@glenn-jocher 
Fixed! Turns out it was the number of workers! However, it still puzzles me, as I requested 50 GB of RAM, which I would think would have been more than sufficient.

**Comment by glenn-jocher** [comment]
@TheCrafft yes, makes sense. If you are running near your resource limits there is a danger that something may push you over the limit during training. Best practice is to leave a bit of safety buffer, i.e. 10 or 20% rather than try to use 95%+ of your resources.
