### ISSUE TITLE
Can't train on A100s on google Colab

### ISSUE THREAD

**Issue by opassos** [ultralytics/yolov5#4924]
When running the training.py on colab powered by A100s GPUs I get the following error.

A100-SXM4-40GB with CUDA capability sm_80 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70.
If you want to use the A100-SXM4-40GB GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

Same notebook runs fine on all other colab instances

**Comment by glenn-jocher** [comment]
@opassos sure, there's a simple fix that's already shown in the message you pasted:
> If you want to use the A100-SXM4-40GB GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

The more interesting question is how did you find an A100 in Colab?

**Comment by opassos** [comment]
@glenn-jocher Sorry If I am being dumb here, but I couldn't find the answer on that pytorch link. Do you mind elaborating a bit more? Thanks

About the access to A100, I have no clue, just started to pop today (breaking all my notebooks in the process lmao). I do have a colab Pro+ though

**Comment by glenn-jocher** [comment]
@opassos hmm interesting. To resolve the issue you just install pytorch following the directions in https://pytorch.org/get-started/locally/

**Comment by opassos** [comment]
Fixed by installing PyTorch using
`!pip3 install torch==1.9.0+cu111 torchvision==0.10.0+cu111 torchaudio==0.9.0 -f https://download.pytorch.org/whl/torch_stable.html`
