### ISSUE TITLE
How to disable UserWarning: User provided device_type of 'cuda', but CUDA is not available and reduce output per epoch to a single line?.

### ISSUE THREAD

**Issue by RRighart** [ultralytics/yolov5#6692]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I am running Yolov5 on my machine using CPU (there is no GPU). This is giving many warnings that CUDA is not available.
In addition, running a single epoch the logging is taking up many lines like the following output:

```
 Epoch   gpu_mem       box       obj       cls    labels  img_size
  0%|          | 0/180 [00:00<?, ?it/s]                                         /usr/local/lib/python3.8/dist-packages/torch/autocast_mode.py:141: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
  warnings.warn('User provided device_type of \'cuda\', but CUDA is not available. Disabling')
       0/2        0G   0.08552    0.0316   0.01973         3       640:   1%|   /usr/local/lib/python3.8/dist-packages/torch/autocast_mode.py:141: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
  warnings.warn('User provided device_type of \'cuda\', but CUDA is not available. Disabling')
       0/2        0G   0.08275   0.03398   0.02043         3       640:   1%|   /usr/local/lib/python3.8/dist-packages/torch/autocast_mode.py:141: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
  warnings.warn('User provided device_type of \'cuda\', but CUDA is not available. Disabling')
       0/2        0G   0.06593    0.0328     0.017         2       640:   2%|▏  /usr/local/lib/python3.8/dist-packages/torch/autocast_mode.py:141: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling 
```

In Kaggle running with CPU this issue is not occurring, it is just taking a single line for each epoch.

Is there a setting where I can reduce this output to a single line per epoch, like in Kaggle?

**Comment by glenn-jocher** [comment]
TODO: try     
```
warnings.filterwarnings(action='ignore', category=torch.jit.TracerWarning)  # suppress TracerWarning
```

**Comment by glenn-jocher** [comment]
@RRighart good news 😃! Your original issue may now be fixed ✅ in PR #6706. To receive this update:
- **[Git](https://github.com/ultralytics/yolov5)** – `git pull` from within your `yolov5/` directory or `git clone https://github.com/ultralytics/yolov5` again
- **[PyTorch Hub](https://pytorch.org/hub/ultralytics_yolov5/)** – Force-reload `model = torch.hub.load('ultralytics/yolov5', 'yolov5s', force_reload=True)`
- **[Notebooks](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb)** – View updated notebooks  <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/yolov5)** – `sudo docker pull ultralytics/yolov5:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and informing us of the problem. Please let us know if this update resolves the issue for you, and feel free to inform us of any other **issues** you discover or **feature requests** that come to mind. Happy trainings with YOLOv5 🚀!

**Comment by ok-kewei** [comment]
I encountered the same error ".. but CUDA is not available...." and solved it by installing the nvidia driver. 
1. sudo apt-get update
2. sudo apt-get install nvidia-driver-418 (depends on the model of your nvidia)

**Comment by glenn-jocher** [comment]
That's great, @ok-kewei! Installing the correct Nvidia driver resolved your CUDA availability issue. It's important to have the necessary drivers for GPU acceleration. For users with GPUs, this installation should provide access to CUDA and enable faster training and inference. For those using CPUs only, this won't apply, and the default CPU mode should work perfectly. If you have any further questions or need more assistance, please feel free to ask. Happy training with YOLOv5!
