### ISSUE TITLE
Runtime CUDA error

### ISSUE THREAD

**Issue by belliriccardo** [ultralytics/yolov5#7181]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar bug report.

### YOLOv5 Component

Detection

### Bug

Hi, I'm using a cutsom trained yolov5 model based on yolov5s. My pc is rather new and has an i7-11370H cpu and geforce rtx 3050ti; the driver's version is 510.54, cuda version 11.6 (from `nvidia-smi`). When I try to evaluate the model I get this rather nasty error:

```
Fusing layers... 
Model summary: 213 layers, 7012822 parameters, 0 gradients
Adding AutoShape... 
Traceback (most recent call last):
  File "/home/username/Desktop/prog/scripts/testmodel.py", line 60, in <module>
    results = model(grayimg)
  File "/home/username/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/username/.local/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/username/Desktop/prog/scripts/./yolov5/models/common.py", line 560, in forward
    y = self.model(x, augment, profile)  # forward
  File "/home/username/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/username/Desktop/prog/scripts/./yolov5/models/common.py", line 408, in forward
    y = self.model(im) if self.jit else self.model(im, augment=augment, visualize=visualize)
  File "/home/username/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/username/Desktop/prog/scripts/./yolov5/models/yolo.py", line 126, in forward
    return self._forward_once(x, profile, visualize)  # single-scale inference, train
  File "/home/username/Desktop/prog/scripts/./yolov5/models/yolo.py", line 149, in _forward_once
    x = m(x)  # run
  File "/home/username/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/username/Desktop/prog/scripts/./yolov5/models/common.py", line 50, in forward_fuse
    return self.act(self.conv(x))
  File "/home/username/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/username/.local/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 447, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/username/.local/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 443, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`
```

I also did get before another cuDNN runtime error similar to the one described [here](https://github.com/pytorch/pytorch/issues/45769), and with the option `torch.backends.cudnn.enabled = False` it did work on another computer of mine. The other pc I'm talking about has a GTX 920MX, and the inference worked fine (I trained the model on colab for convenience). I found that's it's not a very popular error and all the fixes I tried don't seem to work, I've seen [this](https://discuss.pytorch.org/t/cublas-status-execution-failed-when-calling-cublassgemm-handle-opa-opb-m-n-k-alpha-a-lda-b-ldb-beta-c-ldc/116740/19) thread but it looks like it's a dead end. I also wanted to keep using yolov5 for its performance/convenience but this is a showstopper for me for now. I hope I have provided enough information!

### Environment

OS: Ubuntu 20.04
Python: 3.8.10
Other info about the installation:
```
torch.__version__
    1.11.0+cu113
torch.cuda.get_arch_list()
    ['sm_37', 'sm_50', 'sm_60', 'sm_70', 'sm_75', 'sm_80', 'sm_86']
```

### Minimal Reproducible Example

The bug happens in a regular forward call, this is the snippet, I don't think the rest matters too much because it did work exactly like this on another pc

```
model = torch.hub.load('./yolov5', 'custom', path='model/best.pt', source='local')
torch.backends.cudnn.enabled = False
results = model(grayimg)
```

EDIT: I just realized I didn't give context on `grayimg`; it's a grayscale `cv2` image

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by glenn-jocher** [comment]
@belliriccardo it appears you may have environment problems. Please ensure you meet all dependency requirements if you are attempting to run YOLOv5 locally.  If in doubt, create a new virtual [Python 3.9](https://www.python.org/) environment, clone the latest repo ([code changes daily](https://github.com/ultralytics/yolov5/commits/master)), and `pip install` [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) again from scratch.

💡 ProTip! Try one of our verified environments below if you are having trouble with your local environment.


## Requirements

[**Python>=3.7.0**](https://www.python.org/) with all [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt) installed including [**PyTorch>=1.7**](https://pytorch.org/get-started/locally/). To get started:
```bash
git clone https://github.com/ultralytics/yolov5  # clone
cd yolov5
pip install -r requirements.txt  # install
```

[Models](https://github.com/ultralytics/yolov5/tree/master/models) and [datasets](https://github.com/ultralytics/yolov5/tree/master/data) download automatically from the latest YOLOv5 [release](https://github.com/ultralytics/yolov5/releases) when first requested.

## Environments

YOLOv5 may be run in any of the following up-to-date verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn), [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/) preinstalled):

- **Google Colab and Kaggle** notebooks with free GPU: <a href="https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/models/ultralytics/yolov5"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **Google Cloud** Deep Learning VM. See [GCP Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)
- **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)
- **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/) <a href="https://hub.docker.com/r/ultralytics/yolov5"><img src="https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker" alt="Docker Pulls"></a>


## Status

![CI CPU testing](https://github.com/ultralytics/yolov5/workflows/CI%20CPU%20testing/badge.svg)

If this badge is green, all [YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions) Continuous Integration (CI) tests are currently passing. CI tests verify correct operation of YOLOv5 training ([train.py](https://github.com/ultralytics/yolov5/blob/master/train.py)), validation ([val.py](https://github.com/ultralytics/yolov5/blob/master/val.py)), inference ([detect.py](https://github.com/ultralytics/yolov5/blob/master/detect.py)) and export ([export.py](https://github.com/ultralytics/yolov5/blob/master/export.py)) on MacOS, Windows, and Ubuntu every 24 hours and on every commit.

**Comment by belliriccardo** [comment]
Hm, that is really strange because it was already a fresh install, but I'll try it nevertheless! I was a bit worried because I tried uninstalling and reinstalling some specific versions of pytorch as I had similar problems with some specific versions in the recent past, and I never encountered any error similar to this. I was also looking forward to the docker image, I'll test that as well if this procedure doesn't go well. Right now I don't have access to the other pc, I'll update you tomorrow as soon as I get my hands on it.
Anyways, thanks for the quick reply!

**Comment by glenn-jocher** [comment]
@belliriccardo Docker might be a good option if you are trying to run locally.

**Comment by belliriccardo** [comment]
Yeah, the fact is that I need the inference to run in a python script (and not calling it separately like `python detect.py --weights etc`), and I'm not very familiar with docker, like, at all. But if it works, it's gonna be worthwhile to learn for sure.

**Comment by belliriccardo** [comment]
Ok, I just created a new environment using `python3 -m venv`, and installing only the requirements on the .txt file; after running my script I get:

```
/home/username/Desktop/prog/scripts/env/lib/python3.8/site-packages/torch/cuda/__init__.py:145: UserWarning: 
NVIDIA GeForce RTX 3050 Ti Laptop GPU with CUDA capability sm_86 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70.
If you want to use the NVIDIA GeForce RTX 3050 Ti Laptop GPU GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
YOLOv5 🚀 v6.1-73-gd51f9b2 torch 1.11.0+cu102 CUDA:0 (NVIDIA GeForce RTX 3050 Ti Laptop GPU, 3911MiB)

Traceback (most recent call last):
  File "/home/username/Desktop/prog/scripts/./yolov5/hubconf.py", line 46, in _create
    model = DetectMultiBackend(path, device=device)  # download/load FP32 model
  File "/home/username/Desktop/prog/scripts/./yolov5/models/common.py", line 306, in __init__
    model = attempt_load(weights if isinstance(weights, list) else w, map_location=device)
  File "/home/username/Desktop/prog/scripts/./yolov5/models/experimental.py", line 97, in attempt_load
    ckpt = (ckpt.get('ema') or ckpt['model']).float()  # FP32 model
  File "/home/username/Desktop/prog/scripts/env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 743, in float
    return self._apply(lambda t: t.float() if t.is_floating_point() else t)
  File "/home/username/Desktop/prog/scripts/./yolov5/models/yolo.py", line 236, in _apply
    self = super()._apply(fn)
  File "/home/username/Desktop/prog/scripts/env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 578, in _apply
    module._apply(fn)
  File "/home/username/Desktop/prog/scripts/env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 578, in _apply
    module._apply(fn)
  File "/home/username/Desktop/prog/scripts/env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 578, in _apply
    module._apply(fn)
  File "/home/username/Desktop/prog/scripts/env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 601, in _apply
    param_applied = fn(param)
  File "/home/username/Desktop/prog/scripts/env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 743, in <lambda>
    return self._apply(lambda t: t.float() if t.is_floating_point() else t)
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "testmodel.py", line 11, in <module>
    model = torch.hub.load('./yolov5', 'custom',
  File "/home/username/Desktop/prog/scripts/env/lib/python3.8/site-packages/torch/hub.py", line 404, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "/home/username/Desktop/prog/scripts/env/lib/python3.8/site-packages/torch/hub.py", line 433, in _load_local
    model = entry(*args, **kwargs)
  File "/home/username/Desktop/prog/scripts/./yolov5/hubconf.py", line 70, in custom
    return _create(path, autoshape=autoshape, verbose=verbose, device=device)
  File "/home/username/Desktop/prog/scripts/./yolov5/hubconf.py", line 65, in _create
    raise Exception(s) from e
Exception: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.. Cache may be out of date, try `force_reload=True` or see https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading for help.
```

But I have already encountered this issue in the past, and I solved by manually updating torch from the website with:
`pip3 install -U  torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu113`

After this, when I run it again (always in the same env) I get a different error message:

```
YOLOv5 🚀 v6.1-73-gd51f9b2 torch 1.11.0+cu113 CUDA:0 (NVIDIA GeForce RTX 3050 Ti Laptop GPU, 3911MiB)

Fusing layers... 
Model summary: 213 layers, 7012822 parameters, 0 gradients
Adding AutoShape... 
Traceback (most recent call last):
  File "testmodel.py", line 62, in <module>
    results = model(grayimg)
  File "/home/username/Desktop/prog/scripts/env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/username/Desktop/prog/scripts/env/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/username/Desktop/prog/scripts/./yolov5/models/common.py", line 560, in forward
    y = self.model(x, augment, profile)  # forward
  File "/home/username/Desktop/prog/scripts/env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/username/Desktop/prog/scripts/./yolov5/models/common.py", line 408, in forward
    y = self.model(im) if self.jit else self.model(im, augment=augment, visualize=visualize)
  File "/home/username/Desktop/prog/scripts/env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/username/Desktop/prog/scripts/./yolov5/models/yolo.py", line 129, in forward
    return self._forward_once(x, profile, visualize)  # single-scale inference, train
  File "/home/username/Desktop/prog/scripts/./yolov5/models/yolo.py", line 152, in _forward_once
    x = m(x)  # run
  File "/home/username/Desktop/prog/scripts/env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/username/Desktop/prog/scripts/./yolov5/models/common.py", line 50, in forward_fuse
    return self.act(self.conv(x))
  File "/home/username/Desktop/prog/scripts/env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/username/Desktop/prog/scripts/env/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 447, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/username/Desktop/prog/scripts/env/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 443, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: cuDNN error: CUDNN_STATUS_MAPPING_ERROR
```

But then again, I already know this error as well (unfortunately), and I can temporarily "fix" it by setting `torch.backends.cudnn.enabled = False`. After running the script this time I get to where I was at the beginning:

```
YOLOv5 🚀 v6.1-73-gd51f9b2 torch 1.11.0+cu113 CUDA:0 (NVIDIA GeForce RTX 3050 Ti Laptop GPU, 3911MiB)

Fusing layers... 
Model summary: 213 layers, 7012822 parameters, 0 gradients
Adding AutoShape... 
Traceback (most recent call last):
  File "testmodel.py", line 62, in <module>
    results = model(grayimg)
  File "/home/username/Desktop/prog/scripts/env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/username/Desktop/prog/scripts/env/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/username/Desktop/prog/scripts/./yolov5/models/common.py", line 560, in forward
    y = self.model(x, augment, profile)  # forward
  File "/home/username/Desktop/prog/scripts/env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/username/Desktop/prog/scripts/./yolov5/models/common.py", line 408, in forward
    y = self.model(im) if self.jit else self.model(im, augment=augment, visualize=visualize)
  File "/home/username/Desktop/prog/scripts/env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/username/Desktop/prog/scripts/./yolov5/models/yolo.py", line 129, in forward
    return self._forward_once(x, profile, visualize)  # single-scale inference, train
  File "/home/username/Desktop/prog/scripts/./yolov5/models/yolo.py", line 152, in _forward_once
    x = m(x)  # run
  File "/home/username/Desktop/prog/scripts/env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/username/Desktop/prog/scripts/./yolov5/models/common.py", line 50, in forward_fuse
    return self.act(self.conv(x))
  File "/home/username/Desktop/prog/scripts/env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/username/Desktop/prog/scripts/env/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 447, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/username/Desktop/prog/scripts/env/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 443, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`
```

And there we go! As I said, on my other computer this model worked well before, and I don't think it's a model problem since I trained it on a third gpu, from colab. Hope this helps to narrow down the issue.

In the meanwhile, I'll be trying the docker images; even if it's not very convenient for me as of now, I can't afford to be stuck

**Comment by glenn-jocher** [comment]
@belliriccardo this is not a YOLOv5 issue but rather a PyTorch issue. See https://pytorch.org/get-started/locally/, also recommend you try Docker

**Comment by belliriccardo** [comment]
I have tested another setup and.. well, let's just say that the behavior I get is pretty weird. I have another camera, and when I try to do the forward pass (inference) with that other image, everything goes fine, the rest of my program executes well and I get the results I need. The fact is, these two `cv2` images are (or appear to be at least) perfectly identical. Both `numpy.ndarray`s, with the same shape and precision. Even the values are in the accepted ranges (no `inf` or `nan` like I got with other setups). Now I'm even more at a loss at what could be causing this issue. I'll try to narrow down the problem tomorrow, as it looks like there is something wrong with my 2nd setup. I'll keep this issue posted, and if I figure something out or get extra info i'll update/close it. Thx

**Comment by belliriccardo** [comment]
I have solved my issue, and I'll close the bug report since it's not a yolov5 bug.
For anyone else in the future that will encounter a similar problem, here's my solution: I was using another application (ZED SDK) in conjunction with yolov5, and they were both using their own CUDA context. You can find [here](https://github.com/stereolabs/zed-python-api/issues/154) more detail on how to solve it; basically either make the two components share the same context, or split the program in two different threads with two different contexts (which is the approach I used). Now everything works like a charm!

**Comment by AayushAgrawal2003** [comment]
Try building PyTorch from the source rather than the requirements file. This worked for me.

[PyTorch Installation ](https://pytorch.org/get-started/previous-versions/)

```
# ROCM 5.1.1 (Linux only)
pip install torch==1.12.0+rocm5.1.1 torchvision==0.13.0+rocm5.1.1 torchaudio==0.12.0 --extra-index-url  https://download.pytorch.org/whl/rocm5.1.1
# CUDA 11.6
pip install torch==1.12.0+cu116 torchvision==0.13.0+cu116 torchaudio==0.12.0 --extra-index-url https://download.pytorch.org/whl/cu116
# CUDA 11.3
pip install torch==1.12.0+cu113 torchvision==0.13.0+cu113 torchaudio==0.12.0 --extra-index-url https://download.pytorch.org/whl/cu113
# CUDA 10.2
pip install torch==1.12.0+cu102 torchvision==0.13.0+cu102 torchaudio==0.12.0 --extra-index-url https://download.pytorch.org/whl/cu102
# CPU only
pip install torch==1.12.0+cpu torchvision==0.13.0+cpu torchaudio==0.12.0 --extra-index-url https://download.pytorch.org/whl/cpu
```

Download based on CUDA version 

```
nvcc --version #To check CUDA version
```

**Comment by glenn-jocher** [comment]
@AayushAgrawal2003 glad to hear you were able to identify and resolve the issue! Thank you for sharing your solution as it may help others in the future. If you have any more questions or run into any other issues, feel free to let us know. Good luck with your future projects!
